<?php
	
	class AppFieldException extends Exception {
		const ERROR_APPLICATION_FIELD_NAME          = 'ERROR_APPLICATION_FIELD_EMPTY_NAME';
		const ERROR_APPLICATION_FIELD_DUPLICATE     = 'ERROR_APPLICATION_FIELD_DUPLICATE';
		const ERROR_APPLICATION_FIELD_HANDLE_CLASS  = 'ERROR_APPLICATION_FIELD_EMPTY_HANDLE_CLASS';
		const ERROR_APPLICATION_FIELD_HANDLE_METHOD = 'ERROR_APPLICATION_FIELD_EMPTY_HANDLE_METHOD';
		const ERROR_APPLICATION_FIELD_MODULE        = 'ERROR_APPLICATION_FIELD_EMPTY_MODULE_NAME';
	}
