<?php

	class ApplicationException extends Exception {
		const ERROR_APPLICATION_DUPLICATE_CODE      = 'ERROR_APPLICATION_DUPLICATE_CODE';
		const ERROR_APPLICATION_EMPTY               = 'ERROR_APPLICATION_EMPTY';
		const ERROR_APPLICATION_EMPTY_CATEGORY_ID   = 'ERROR_APPLICATION_EMPTY_CATEGORY_ID';
		const ERROR_APPLICATION_EMPTY_CODE          = 'ERROR_APPLICATION_EMPTY_CODE';
		const ERROR_APPLICATION_EMPTY_MODULES       = 'ERROR_APPLICATION_EMPTY_MODULES';
		const ERROR_APPLICATION_EMPTY_NAME          = 'ERROR_APPLICATION_EMPTY_NAME';
		const ERROR_APPLICATION_EMPTY_PROFILE       = 'ERROR_APPLICATION_EMPTY_PROFILE';
		const ERROR_APPLICATION_EMPTY_URL           = 'ERROR_APPLICATION_EMPTY_URL';
		const ERROR_APPLICATION_INVALID_CATEGORY_ID = 'ERROR_APPLICATION_INVALID_CATEGORY_ID';
		const ERROR_APPLICATION_INVALID_MODULE      = 'ERROR_APPLICATION_INVALID_MODULE';
		const ERROR_APPLICATION_INVALID_PROFILE_ID  = 'ERROR_APPLICATION_INVALID_PROFILE_ID';

	}
