<?php

	class ApplicationSubscriptionException extends Exception {
		const ERROR_APPLICATION_SUBSCRIPTION_EMPTY_APPLICATION_CODE  = 'ERROR_APPLICATION_SUBSCRIPTION_EMPTY_APPLICATION_CODE';
		const ERROR_APPLICATION_SUBSCRIPTION_EMPTY_INSTANCE_CODE     = 'ERROR_APPLICATION_SUBSCRIPTION_EMPTY_INSTANCE_CODE';
		const ERROR_APPLICATION_SUBSCRIPTION_EMPTY_REGISTRATION_DATE = 'ERROR_APPLICATION_SUBSCRIPTION_EMPTY_REGISTRATION_DATE';
		const ERROR_APPLICATION_SUBSCRIPTION_EMPTY_STATUS            = 'ERROR_APPLICATION_SUBSCRIPTION_EMPTY_STATUS';

	}
