<?php

	class BackgroundTaskActionConfigurationException extends Exception {
		const ERROR_BACKGROUND_TASK_ACTION_CONFIGURATION_EMPTY                = 'ERROR_BACKGROUND_TASK_ACTION_EMPTY';
		const ERROR_BACKGROUND_TASK_ACTION_CONFIGURATION_EMPTY_HANDLER_CLASS  = 'ERROR_BACKGROUND_TASK_ACTION_EMPTY_HANDLER_CLASS';
		const ERROR_BACKGROUND_TASK_ACTION_CONFIGURATION_EMPTY_HANDLER_METHOD = 'ERROR_BACKGROUND_TASK_ACTION_EMPTY_HANDLER_METHOD';
		const ERROR_BACKGROUND_TASK_ACTION_CONFIGURATION_EMPTY_TYPE           = 'ERROR_BACKGROUND_TASK_ACTION_EMPTY_TYPE';
		const ERROR_BACKGROUND_TASK_ACTION_CONFIGURATION_INVALID_PARAMETER    = 'ERROR_BACKGROUND_TASK_ACTION_INVALID_PARAMETER';
		const ERROR_BACKGROUND_TASK_ACTION_CONFIGURATION_INVALID_TYPE         = 'ERROR_BACKGROUND_TASK_ACTION_INVALID_TYPE';

	}
