<?php

	class BackgroundTaskParameterException extends Exception {
		const ERROR_BACKGROUND_TASK_PARAMETER_EMPTY              = 'ERROR_BACKGROUND_TASK_PARAMETER_EMPTY';
		const ERROR_BACKGROUND_TASK_PARAMETER_EMPTY_ACTION_NAME  = 'ERROR_BACKGROUND_TASK_PARAMETER_EMPTY_ACTION_NAME';
		const ERROR_BACKGROUND_TASK_PARAMETER_EMPTY_ACTION_TYPE  = 'ERROR_BACKGROUND_TASK_PARAMETER_EMPTY_ACTION_TYPE';
		const ERROR_BACKGROUND_TASK_PARAMETER_EMPTY_EXPANDED_KEY = 'ERROR_BACKGROUND_TASK_PARAMETER_EMPTY_EXPANDED_KEY';
		const ERROR_BACKGROUND_TASK_PARAMETER_EMPTY_NAME         = 'ERROR_BACKGROUND_TASK_PARAMETER_EMPTY_NAME';
		const ERROR_BACKGROUND_TASK_PARAMETER_EMPTY_SEQUENCE     = 'ERROR_BACKGROUND_TASK_PARAMETER_EMPTY_SEQUENCE';
		const ERROR_BACKGROUND_TASK_PARAMETER_INVALID            = 'ERROR_BACKGROUND_TASK_PARAMETER_INVALID';
		const ERROR_BACKGROUND_TASK_PARAMETER_INVALID_OPTION     = 'ERROR_BACKGROUND_TASK_PARAMETER_INVALID_OPTION';
		const ERROR_BACKGROUND_TASK_PARAMETER_INVALID_TYPE       = 'ERROR_BACKGROUND_TASK_PARAMETER_INVALID_TYPE';

	}
