<?php

	class BackgroundTaskException extends Exception {
		const ERROR_BACKGROUND_TASK_DUPLICATE_NAME       = 'ERROR_BACKGROUND_TASK_DUPLICATE_NAME';
		const ERROR_BACKGROUND_TASK_EMPTY                = 'ERROR_BACKGROUND_TASK_EMPTY';
		const ERROR_BACKGROUND_TASK_EMPTY_ACTIONS        = 'ERROR_BACKGROUND_TASK_EMPTY_ACTIONS';
		const ERROR_BACKGROUND_TASK_EMPTY_EVENT          = 'ERROR_BACKGROUND_TASK_EMPTY_EVENT';
		const ERROR_BACKGROUND_TASK_EMPTY_EVENT_INSTANT  = 'ERROR_BACKGROUND_TASK_EMPTY_EVENT_INSTANT';
		const ERROR_BACKGROUND_TASK_EMPTY_FREQUENCY      = 'ERROR_BACKGROUND_TASK_EMPTY_FREQUENCY';
		const ERROR_BACKGROUND_TASK_EMPTY_NAME           = 'ERROR_BACKGROUND_TASK_EMPTY_NAME';
		const ERROR_BACKGROUND_TASK_EMPTY_SCOPE          = 'ERROR_BACKGROUND_TASK_EMPTY_SCOPE';
		const ERROR_BACKGROUND_TASK_EMPTY_STATUS         = 'ERROR_BACKGROUND_TASK_EMPTY_STATUS';
		const ERROR_BACKGROUND_TASK_EMPTY_TRIGGER        = 'ERROR_BACKGROUND_TASK_EMPTY_TRIGGER';
		const ERROR_BACKGROUND_TASK_INVALID_ACTION       = 'ERROR_BACKGROUND_TASK_INVALID_ACTION';
		const ERROR_BACKGROUND_TASK_INVALID_EVENT        = 'ERROR_BACKGROUND_TASK_INVALID_EVENT';
		const ERROR_BACKGROUND_TASK_INVALID_FILTER_GROUP = 'ERROR_BACKGROUND_TASK_INVALID_FILTER_GROUP';
		const ERROR_BACKGROUND_TASK_INVALID_MODULE_NAME  = 'ERROR_BACKGROUND_TASK_INVALID_MODULE_NAME';

	}
