<?php

	class BackgroundTaskEventException extends Exception {
		const ERROR_BACKGROUND_TASK_EVENT_EMPTY             = 'ERROR_BACKGROUND_TASK_EVENT_EMPTY';
		const ERROR_BACKGROUND_TASK_EVENT_EMPTY_DESCRIPTION = 'ERROR_BACKGROUND_TASK_EVENT_EMPTY_DESCRIPTION';
		const ERROR_BACKGROUND_TASK_EVENT_EMPTY_NAME        = 'ERROR_BACKGROUND_TASK_EVENT_EMPTY_NAME';
		const ERROR_BACKGROUND_TASK_EVENT_EMPTY_SCOPE       = 'ERROR_BACKGROUND_TASK_EVENT_EMPTY_SCOPE';

	}
