<?php

	class BackgroundTaskParameterConfigurationException extends Exception {
		const ERROR_BACKGROUND_TASK_PARAMETER_CONFIGURATION_EMPTY_ACTION_TYPE     = 'ERROR_BACKGROUND_TASK_PARAMETER_CONFIGURATION_EMPTY_ACTION_TYPE';
		const ERROR_BACKGROUND_TASK_PARAMETER_CONFIGURATION_EMPTY_PARAMETER_NAME  = 'ERROR_BACKGROUND_TASK_PARAMETER_CONFIGURATION_EMPTY_PARAMETER_NAME';
		const ERROR_BACKGROUND_TASK_PARAMETER_CONFIGURATION_EMPTY_PARAMETER_ORDER = 'ERROR_BACKGROUND_TASK_PARAMETER_CONFIGURATION_EMPTY_PARAMETER_ORDER';
		const ERROR_BACKGROUND_TASK_PARAMETER_CONFIGURATION_EMPTY_PARAMETER_TYPE  = 'ERROR_BACKGROUND_TASK_PARAMETER_CONFIGURATION_EMPTY_PARAMETER_TYPE';

	}
