<?php

	class BackgroundTaskCategoryException extends Exception {
		const ERROR_BACKGROUND_TASK_CATEGORY_EMPTY             = 'ERROR_BACKGROUND_TASK_CATEGORY_EMPTY';
		const ERROR_BACKGROUND_TASK_CATEGORY_EMPTY_DESCRIPTION = 'ERROR_BACKGROUND_TASK_CATEGORY_EMPTY_DESCRIPTION';
		const ERROR_BACKGROUND_TASK_CATEGORY_EMPTY_NAME        = 'ERROR_BACKGROUND_TASK_CATEGORY_EMPTY_NAME';

	}
