<?php

	class BackgroundTaskConfigurationException extends Exception {
		const ERROR_BACKGROUND_TASK_CONFIGURATION_EMPTY            = 'ERROR_BACKGROUND_TASK_CONFIGURATION_EMPTY';
		const ERROR_BACKGROUND_TASK_CONFIGURATION_EMPTY_ACTIONS    = 'ERROR_BACKGROUND_TASK_CONFIGURATION_EMPTY_ACTIONS';
		const ERROR_BACKGROUND_TASK_CONFIGURATION_EMPTY_EVENTS     = 'ERROR_BACKGROUND_TASK_CONFIGURATION_EMPTY_EVENTS';
		const ERROR_BACKGROUND_TASK_CONFIGURATION_INVALID_ACTION   = 'ERROR_BACKGROUND_TASK_CONFIGURATION_INVALID_ACTION';
		const ERROR_BACKGROUND_TASK_CONFIGURATION_INVALID_CATEGORY = 'ERROR_BACKGROUND_TASK_CONFIGURATION_INVALID_CATEGORY';
		const ERROR_BACKGROUND_TASK_CONFIGURATION_INVALID_EVENT    = 'ERROR_BACKGROUND_TASK_CONFIGURATION_INVALID_EVENT';

	}
