<?php

	class BlockException extends Exception {
		const ERROR_BLOCK_EMPTY               = 'ERROR_BLOCK_EMPTY';
		const ERROR_BLOCK_EMPTY_LABEL         = 'ERROR_BLOCK_EMPTY_LABEL';
		const ERROR_BLOCK_EMPTY_MODULE_NAME   = 'ERROR_BLOCK_EMPTY_MODULE_NAME';
		const ERROR_BLOCK_INVALID_FIELD       = 'ERROR_BLOCK_INVALID_FIELD';
		const ERROR_BLOCK_INVALID_FIELDS      = 'ERROR_BLOCK_INVALID_FIELDS';
		const ERROR_BLOCK_INVALID_MODULE_NAME = 'ERROR_BLOCK_INVALID_MODULE_NAME';

	}
