<?php

	class ButtonException extends Exception {
		const ERROR_BUTTON_EMPTY               = 'ERROR_BUTTON_EMPTY';
		const ERROR_BUTTON_EMPTY_ACTION        = 'ERROR_BUTTON_EMPTY_ACTION';
		const ERROR_BUTTON_EMPTY_LABEL         = 'ERROR_BUTTON_EMPTY_LABEL';
		const ERROR_BUTTON_EMPTY_LOCATION      = 'ERROR_BUTTON_EMPTY_LOCATION';
		const ERROR_BUTTON_EMPTY_MODULE_NAME   = 'ERROR_BUTTON_EMPTY_MODULE_NAME';
		const ERROR_BUTTON_EMPTY_STYLE         = 'ERROR_BUTTON_EMPTY_STYLE';
		const ERROR_BUTTON_EMPTY_TYPE          = 'ERROR_BUTTON_EMPTY_TYPE';
		const ERROR_BUTTON_INVALID_MODULE_NAME = 'ERROR_BUTTON_INVALID_MODULE_NAME';

	}
