<?php

	class CalculationSystemException extends Exception {
		const ERROR_CALCULATION_SYSTEM_EMPTY_CALCUALTED_DATA     = 'ERROR_CALCULATION_SYSTEM_EMPTY_CALCUALTED_DATA';
		const ERROR_CALCULATION_SYSTEM_EMPTY_FIRST_ELEMENT       = 'ERROR_CALCULATION_SYSTEM_EMPTY_FIRST_ELEMENT';
		const ERROR_CALCULATION_SYSTEM_EMPTY_FIRST_ELEMENT_TYPE  = 'ERROR_CALCULATION_SYSTEM_EMPTY_FIRST_ELEMENT_TYPE';
		const ERROR_CALCULATION_SYSTEM_EMPTY_GROUP_OPERATION     = 'ERROR_CALCULATION_SYSTEM_EMPTY_GROUP_OPERATION';
		const ERROR_CALCULATION_SYSTEM_EMPTY_MODULE_NAME         = 'ERROR_CALCULATION_SYSTEM_EMPTY_MODULE_NAME';
		const ERROR_CALCULATION_SYSTEM_EMPTY_NAME                = 'ERROR_CALCULATION_SYSTEM_EMPTY_NAME';
		const ERROR_CALCULATION_SYSTEM_EMPTY_OPERATION           = 'ERROR_CALCULATION_SYSTEM_EMPTY_OPERATION';
		const ERROR_CALCULATION_SYSTEM_EMPTY_SECOND_ELEMENT      = 'ERROR_CALCULATION_SYSTEM_EMPTY_SECOND_ELEMENT';
		const ERROR_CALCULATION_SYSTEM_EMPTY_SECOND_ELEMENT_TYPE = 'ERROR_CALCULATION_SYSTEM_EMPTY_SECOND_ELEMENT_TYPE';
		const ERROR_CALCULATION_SYSTEM_EMPTY_SQL                 = 'ERROR_CALCULATION_SYSTEM_EMPTY_SQL';
		const ERROR_CALCULATION_SYSTEM_EMPTY_UPDATED_DATE        = 'ERROR_CALCULATION_SYSTEM_EMPTY_UPDATED_DATE';
		const ERROR_CALCULATION_SYSTEM_UPDATED_DATE_FORMAT       = 'ERROR_CALCULATION_SYSTEM_EMPTY_UPDATED_FORMAT';
	}
