<?php

	class CalculationElementException extends Exception {
		const ERROR_CALCULATION_ELEMENT_EMPTY_COLUMNA_NAME        = 'ERROR_CALCULATION_ELEMENT_EMPTY_COLUMNA_NAME';
		const ERROR_CALCULATION_ELEMENT_EMPTY_MODULE_NAME         = 'ERROR_CALCULATION_ELEMENT_EMPTY_MODULE_NAME';
		const ERROR_CALCULATION_ELEMENT_EMPTY_NAME                = 'ERROR_CALCULATION_ELEMENT_EMPTY_NAME';
		const ERROR_CALCULATION_ELEMENT_EMPTY_OPERATION_NAME      = 'ERROR_CALCULATION_ELEMENT_EMPTY_OPERATION_NAME';
		const ERROR_CALCULATION_ELEMENT_EMPTY_UPDATED_DATE        = 'ERROR_CALCULATION_ELEMENT_EMPTY_UPDATED_DATE';
		const ERROR_CALCULATION_ELEMENT_UPDATED_DATE_FORMAT       = 'ERROR_CALCULATION_ELEMENT_EMPTY_UPDATED_FORMAT';
	}
