<?php

	class CalendarViewRuleException extends Exception {
		const ERROR_CALENDAR_VIEW_RULE_EMPTY_BACKGROUND_COLOR   = 'ERROR_CALENDAR_VIEW_RULE_EMPTY_BACKGROUND_COLOR';
		const ERROR_CALENDAR_VIEW_RULE_EMPTY_FIELD_NAME         = 'ERROR_CALENDAR_VIEW_RULE_EMPTY_FIELD_NAME';
		const ERROR_CALENDAR_VIEW_RULE_EMPTY_MODULE_NAME        = 'ERROR_CALENDAR_VIEW_RULE_EMPTY_MODULE_NAME';
		const ERROR_CALENDAR_VIEW_RULE_EMPTY_OPERATOR           = 'ERROR_CALENDAR_VIEW_RULE_EMPTY_OPERATOR';
		const ERROR_CALENDAR_VIEW_RULE_EMPTY_VIEW_LABEL         = 'ERROR_CALENDAR_VIEW_RULE_EMPTY_VIEW_LABEL';
		const ERROR_CALENDAR_VIEW_RULE_INVALID_BACKGROUND_COLOR = 'ERROR_CALENDAR_VIEW_RULE_INVALID_BACKGROUND_COLOR';
		const ERROR_CALENDAR_VIEW_RULE_INVALID_FIELD_NAME       = 'ERROR_CALENDAR_VIEW_RULE_INVALID_FIELD_NAME';
		const ERROR_CALENDAR_VIEW_RULE_INVALID_MODULE_NAME      = 'ERROR_CALENDAR_VIEW_RULE_INVALID_MODULE_NAME';

	}
