<?php

	class CalendarViewException extends Exception {
		const ERROR_CALENDAR_VIEW_DUPLICATE_LABEL          = 'ERROR_CALENDAR_VIEW_DUPLICATE_LABEL';
		const ERROR_CALENDAR_VIEW_EMPTY                    = 'ERROR_CALENDAR_VIEW_EMPTY';
		const ERROR_CALENDAR_VIEW_EMPTY_APPLICATION_CODES  = 'ERROR_CALENDAR_VIEW_EMPTY_APPLICATION_CODES';
		const ERROR_CALENDAR_VIEW_EMPTY_LABEL              = 'ERROR_CALENDAR_VIEW_EMPTY_LABEL';
		const ERROR_CALENDAR_VIEW_EMPTY_FROM_FIELD_NAME    = 'ERROR_CALENDAR_VIEW_EMPTY_FROM_FIELD_NAME';
		const ERROR_CALENDAR_VIEW_EMPTY_FROM_MODULE_NAME   = 'ERROR_CALENDAR_VIEW_EMPTY_FROM_MODULE_NAME';
		const ERROR_CALENDAR_VIEW_EMPTY_MODULE_NAME        = 'ERROR_CALENDAR_VIEW_EMPTY_MODULE_NAME';
		const ERROR_CALENDAR_VIEW_EMPTY_RULE               = 'ERROR_CALENDAR_VIEW_EMPTY_RULE';
		const ERROR_CALENDAR_VIEW_EMPTY_TITLE_FIELD_NAME   = 'ERROR_CALENDAR_VIEW_EMPTY_TITLE_FIELD_NAME';
		const ERROR_CALENDAR_VIEW_EMPTY_TITLE_MODULE_NAME  = 'ERROR_CALENDAR_VIEW_EMPTY_TITLE_MODULE_NAME';
		const ERROR_CALENDAR_VIEW_INVALID_BACKGROUND_COLOR = 'ERROR_CALENDAR_VIEW_INVALID_BACKGROUND_COLOR';
		const ERROR_CALENDAR_VIEW_INVALID_DATE_FIELD       = 'ERROR_CALENDAR_VIEW_INVALID_DATE_FIELD';
		const ERROR_CALENDAR_VIEW_INVALID_FIELD_NAME       = 'ERROR_CALENDAR_VIEW_INVALID_FIELD_NAME';
		const ERROR_CALENDAR_VIEW_INVALID_MODULE_NAME      = 'ERROR_CALENDAR_VIEW_INVALID_MODULE_NAME';
		const ERROR_CALENDAR_VIEW_INVALID_RULE             = 'ERROR_CALENDAR_VIEW_INVALID_RULE';

	}
