<?php

	class ChartException extends Exception {
		const ERROR_CHART_EMPTY               = 'ERROR_CHART_EMPTY';
		const ERROR_CHART_EMPTY_FIELD_NAME    = 'ERROR_CHART_EMPTY_FIELD_NAME';
		const ERROR_CHART_EMPTY_GROUP_BY      = 'ERROR_CHART_EMPTY_GROUP_BY';
		const ERROR_CHART_EMPTY_MODULE_NAME   = 'ERROR_CHART_EMPTY_MODULE';
		const ERROR_CHART_EMPTY_OPERATION     = 'ERROR_CHART_EMPTY_OPERATION';
		const ERROR_CHART_EMPTY_TITLE         = 'ERROR_CHART_EMPTY_TITLE';
		const ERROR_CHART_EMPTY_TYPE          = 'ERROR_CHART_EMPTY_TYPE';
		const ERROR_CHART_INVALID_FIELD_NAME  = 'ERROR_CHART_INVALID_FIELD_NAME';
		const ERROR_CHART_INVALID_GROUP_BY    = 'ERROR_CHART_INVALID_GROUP_BY';
		const ERROR_CHART_INVALID_MODULE_NAME = 'ERROR_CHART_INVALID_MODULE_NAME';

	}
