<?php

	class DataSharingRequestException extends Exception {
		const ERROR_DATA_SHARING_REQUEST_EMPTY                      = 'ERROR_DATA_SHARING_REQUEST_EMPTY';
		const ERROR_DATA_SHARING_REQUEST_EMPTY_ADDITIONAL_ARGUMENTS = 'ERROR_DATA_SHARING_REQUEST_EMPTY_ADDITIONAL_ARGUMENTS';
		const ERROR_DATA_SHARING_REQUEST_EMPTY_APPLICATION_CODE     = 'ERROR_DATA_SHARING_REQUEST_EMPTY_APPLICATION_CODE';
		const ERROR_DATA_SHARING_REQUEST_EMPTY_CREATED_BY           = 'ERROR_DATA_SHARING_REQUEST_EMPTY_CREATED_BY';
		const ERROR_DATA_SHARING_REQUEST_EMPTY_CREATION_DATE        = 'ERROR_DATA_SHARING_REQUEST_EMPTY_CREATION_DATE';
		const ERROR_DATA_SHARING_REQUEST_EMPTY_FIRST_NAME           = 'ERROR_DATA_SHARING_REQUEST_EMPTY_FIRST_NAME';
		const ERROR_DATA_SHARING_REQUEST_EMPTY_ID                   = 'ERROR_DATA_SHARING_REQUEST_EMPTY_ID';
		const ERROR_DATA_SHARING_REQUEST_EMPTY_LAST_NAME            = 'ERROR_DATA_SHARING_REQUEST_EMPTY_LAST_NAME';
		const ERROR_DATA_SHARING_REQUEST_EMPTY_MODULE_NAME          = 'ERROR_DATA_SHARING_REQUEST_EMPTY_MODULE_NAME';
		const ERROR_DATA_SHARING_REQUEST_EMPTY_PASSWORD             = 'ERROR_DATA_SHARING_REQUEST_EMPTY_PASSWORD';
		const ERROR_DATA_SHARING_REQUEST_EMPTY_PLATFORM             = 'ERROR_DATA_SHARING_REQUEST_EMPTY_PLATFORM';
		const ERROR_DATA_SHARING_REQUEST_EMPTY_RECIPIENT_ADDRESS    = 'ERROR_DATA_SHARING_REQUEST_EMPTY_RECIPIENT_ADDRESS';
		const ERROR_DATA_SHARING_REQUEST_EMPTY_RECORD_IDS           = 'ERROR_DATA_SHARING_REQUEST_EMPTY_RECORD_IDS';
		const ERROR_DATA_SHARING_REQUEST_EMPTY_REPEATED_PASSWORD    = 'ERROR_DATA_SHARING_REQUEST_EMPTY_REPEATED_PASSWORD';
		const ERROR_DATA_SHARING_REQUEST_EMPTY_RULE_ID              = 'ERROR_DATA_SHARING_REQUEST_EMPTY_RULE_ID';
		const ERROR_DATA_SHARING_REQUEST_EMPTY_SOURCE_INSTANCE_CODE = 'ERROR_DATA_SHARING_REQUEST_EMPTY_SOURCE_INSTANCE_CODE';
		const ERROR_DATA_SHARING_REQUEST_EMPTY_STATUS               = 'ERROR_DATA_SHARING_REQUEST_EMPTY_STATUS';
		const ERROR_DATA_SHARING_REQUEST_EMPTY_TARGET_INSTANCE_CODE = 'ERROR_DATA_SHARING_REQUEST_EMPTY_TARGET_INSTANCE_CODE';
		const ERROR_DATA_SHARING_REQUEST_EMPTY_USERS_SERVER         = 'ERROR_DATA_SHARING_REQUEST_EMPTY_USERS_SERVER';
		const ERROR_DATA_SHARING_REQUEST_EXPIRED                    = 'ERROR_DATA_SHARING_REQUEST_EXPIRED';
		const ERROR_DATA_SHARING_REQUEST_INVALID_MODULE_NAME        = 'ERROR_DATA_SHARING_REQUEST_INVALID_MODULE_NAME';
		const ERROR_DATA_SHARING_REQUEST_INVALID_RECORD_ID          = 'ERROR_DATA_SHARING_REQUEST_INVALID_RECORD_ID';
		const ERROR_DATA_SHARING_REQUEST_INVALID_RULE_ID            = 'ERROR_DATA_SHARING_REQUEST_INVALID_RULE_ID';
		const ERROR_DATA_SHARING_REQUEST_INVALID_TOKEN              = 'ERROR_DATA_SHARING_REQUEST_INVALID_TOKEN';
		const ERROR_DATA_SHARING_REQUEST_PASSWORDS_DO_NOT_MATCH     = 'ERROR_DATA_SHARING_REQUEST_PASSWORDS_DO_NOT_MATCH';
		const ERROR_DATA_SHARING_REQUEST_SAME_INSTANCE_RECIPIENT    = 'ERROR_DATA_SHARING_REQUEST_SAME_INSTANCE_RECIPIENT';

	}
