<?php

	class DataSharingSyncException extends Exception {
		const ERROR_DATA_SHARING_SYNC_EMPTY_RULE_ID               = 'ERROR_DATA_SHARING_SYNC_EMPTY_RULE_ID';
		const ERROR_DATA_SHARING_SYNC_EMPTY_SOURCE_EMAIL_ADDRESS  = 'ERROR_DATA_SHARING_SYNC_EMPTY_SOURCE_EMAIL_ADDRESS';
		const ERROR_DATA_SHARING_SYNC_EMPTY_SOURCE_INSTANCE_CODE  = 'ERROR_DATA_SHARING_SYNC_EMPTY_SOURCE_INSTANCE_CODE';
		const ERROR_DATA_SHARING_SYNC_EMPTY_SOURCE_MODULE_NAME    = 'ERROR_DATA_SHARING_SYNC_EMPTY_SOURCE_MODULE_NAME';
		const ERROR_DATA_SHARING_SYNC_EMPTY_SOURCE_RECORD_ID      = 'ERROR_DATA_SHARING_SYNC_EMPTY_SOURCE_RECORD_ID';
		const ERROR_DATA_SHARING_SYNC_EMPTY_TARGET_EMAIL_ADDRESS  = 'ERROR_DATA_SHARING_SYNC_EMPTY_TARGET_EMAIL_ADDRESS';
		const ERROR_DATA_SHARING_SYNC_EMPTY_TARGET_INSTANCE_CODE  = 'ERROR_DATA_SHARING_SYNC_EMPTY_TARGET_INSTANCE_CODE';
		const ERROR_DATA_SHARING_SYNC_EMPTY_TARGET_MODULE_NAME    = 'ERROR_DATA_SHARING_SYNC_EMPTY_TARGET_MODULE_NAME';
		const ERROR_DATA_SHARING_SYNC_EMPTY_TARGET_RECORD_ID      = 'ERROR_DATA_SHARING_SYNC_EMPTY_TARGET_RECORD_ID';

	}
