<?php

	class DataSharingRuleDetailException extends Exception {
		const ERROR_DATA_SHARING_RULE_DETAIL_EMPTY_ACTION_TYPE          = 'ERROR_DATA_SHARING_RULE_DETAIL_EMPTY_ACTION_TYPE';
		const ERROR_DATA_SHARING_RULE_DETAIL_EMPTY_RULE_ID              = 'ERROR_DATA_SHARING_RULE_DETAIL_EMPTY_RULE_ID';
		const ERROR_DATA_SHARING_RULE_DETAIL_EMPTY_SOURCE_MODULE_NAME   = 'ERROR_DATA_SHARING_RULE_DETAIL_EMPTY_SOURCE_MODULE_NAME';
		const ERROR_DATA_SHARING_RULE_DETAIL_EMPTY_TARGET_FIELD_NAME    = 'ERROR_DATA_SHARING_RULE_DETAIL_EMPTY_TARGET_FIELD_NAME';
		const ERROR_DATA_SHARING_RULE_DETAIL_EMPTY_TARGET_MODULE_NAME   = 'ERROR_DATA_SHARING_RULE_DETAIL_EMPTY_TARGET_MODULE_NAME';
		const ERROR_DATA_SHARING_RULE_DETAIL_INVALID_SOURCE_MODULE_NAME = 'ERROR_DATA_SHARING_RULE_DETAIL_INVALID_SOURCE_MODULE_NAME';
		const ERROR_DATA_SHARING_RULE_DETAIL_INVALID_TARGET_FIELD_NAME  = 'ERROR_DATA_SHARING_RULE_DETAIL_INVALID_TARGET_FIELD_NAME';
		const ERROR_DATA_SHARING_RULE_DETAIL_INVALID_TARGET_MODULE_NAME = 'ERROR_DATA_SHARING_RULE_DETAIL_INVALID_TARGET_MODULE_NAME';

	}
