<?php

	class DatabaseException extends Exception {
		const ERROR_UNABLE_TO_CONNECT           = 'ERROR_UNABLE_TO_CONNECT';
		const ERROR_UNABLE_TO_CREATE_DATABASE   = 'ERROR_UNABLE_TO_CREATE_DATABASE';
		const ERROR_UNABLE_TO_CREATE_USER       = 'ERROR_UNABLE_TO_CREATE_USER';
		const ERROR_UNABLE_TO_DELETE_DATABASE   = 'ERROR_UNABLE_TO_DELETE_DATABASE';
		const ERROR_UNABLE_TO_DELETE_USER       = 'ERROR_UNABLE_TO_DELETE_USER';
		const ERROR_UNABLE_TO_GRANT_PERMISSIONS = 'ERROR_UNABLE_TO_GRANT_PERMISSIONS';

	}
