<?php

	class DataSharingRuleException extends Exception {
		const ERROR_DATA_SHARING_RULE_DUPLICATE_NAME      = 'ERROR_DATA_SHARING_RULE_DUPLICATE_NAME';
		const ERROR_DATA_SHARING_RULE_EMPTY               = 'ERROR_DATA_SHARING_RULE_EMPTY';
		const ERROR_DATA_SHARING_RULE_EMPTY_DETAIL        = 'ERROR_DATA_SHARING_RULE_EMPTY_DETAIL';
		const ERROR_DATA_SHARING_RULE_EMPTY_DETAILS       = 'ERROR_DATA_SHARING_RULE_EMPTY_DETAILS';
		const ERROR_DATA_SHARING_RULE_EMPTY_MODULE_NAME   = 'ERROR_DATA_SHARING_RULE_EMPTY_MODULE_NAME';
		const ERROR_DATA_SHARING_RULE_EMPTY_NAME          = 'ERROR_DATA_SHARING_RULE_EMPTY_NAME';
		const ERROR_DATA_SHARING_RULE_EMPTY_STATUS        = 'ERROR_DATA_SHARING_RULE_EMPTY_STATUS';
		const ERROR_DATA_SHARING_RULE_INVALID_DETAIL      = 'ERROR_DATA_SHARING_RULE_INVALID_DETAIL';
		const ERROR_DATA_SHARING_RULE_INVALID_MODULE_NAME = 'ERROR_DATA_SHARING_RULE_INVALID_MODULE_NAME';

	}
