<?php

	class EditableFieldsException extends Exception {
		const ERROR_EDITABLE_FIELD_EMPTY_BUTTON         = 'ERROR_EDITABLE_FIELD_EMPTY_BUTTON';
		const ERROR_EDITABLE_FIELD_EMPTY_BUTTON_NAME    = 'ERROR_EDITABLE_FIELD_EMPTY_BUTTON_NAME';
		const ERROR_EDITABLE_FIELD_EMPTY_EDITABLE_FIELD = 'ERROR_EDITABLE_FIELD_EMPTY_EDITABLE_FIELD';
		const ERROR_EDITABLE_FIELD_EMPTY_FIELD_NAME     = 'ERROR_EDITABLE_FIELD_EMPTY_FIELD_NAME';
		const ERROR_EDITABLE_FIELD_EMPTY_MODULE_NAME    = 'ERROR_EDITABLE_FIELD_EMPTY_MODULE';
		const ERROR_EDITABLE_FIELD_INVALID_BUTTON_NAME  = 'ERROR_EDITABLE_FIELD_INVALID_BUTTON_NAME';
		const ERROR_EDITABLE_FIELD_INVALID_MODULE_NAME  = 'ERROR_EDITABLE_FIELD_INVALID_MODULE_NAME';
	}
