<?php

	class FieldProfileException extends Exception {
		const ERROR_FIELD_PROFILE_EMPTY_PROFILE        = 'ERROR_FIELD_PROFILE_EMPTY_PROFILE';
		const ERROR_FIELD_PROFILE_EMPTY_FIELD_NAME     = 'ERROR_FIELD_PROFILE_EMPTY_FIELD_NAME';
		const ERROR_FIELD_PROFILE_EMPTY_MODULE_NAME    = 'ERROR_FIELD_PROFILE_EMPTY_MODULE_NAME';
		const ERROR_FIELD_PROFILE_EMPTY_PROFILE_NAME   = 'ERROR_FIELD_PROFILE_EMPTY_PROFILE_NAME';
		const ERROR_FIELD_PROFILE_INVALID_FIELD_NAME   = 'ERROR_FIELD_PROFILE_INVALID_FIELD_NAME';
		const ERROR_FIELD_PROFILE_INVALID_MODULE_NAME  = 'ERROR_FIELD_PROFILE_INVALID_MODULE_NAME';
		const ERROR_FIELD_PROFILE_INVALID_PROFILE_NAME = 'ERROR_FIELD_PROFILE_INVALID_PROFILE_NAME';

	}
