<?php

	class FieldModuleReferenceRelationshipException extends Exception {
		const ERROR_FIELD_MODULE_REFERENCE_RELATIONSHIP_EMPTY_FIELD_NAME              = 'ERROR_FIELD_MODULE_REFERENCE_RELATIONSHIP_EMPTY_FIELD_NAME';
		const ERROR_FIELD_MODULE_REFERENCE_RELATIONSHIP_EMPTY_REFERENCED_FIELD_NAME   = 'ERROR_FIELD_MODULE_REFERENCE_RELATIONSHIP_EMPTY_REFERENCED_FIELD_NAME';
		const ERROR_FIELD_MODULE_REFERENCE_RELATIONSHIP_INVALID_FIELD_NAME            = 'ERROR_FIELD_MODULE_REFERENCE_RELATIONSHIP_INVALID_FIELD_NAME';
		const ERROR_FIELD_MODULE_REFERENCE_RELATIONSHIP_INVALID_REFERENCED_FIELD_NAME = 'ERROR_FIELD_MODULE_REFERENCE_RELATIONSHIP_INVALID_REFERENCED_FIELD_NAME';

	}
