<?php

	class FieldModuleReferenceFilterException extends Exception {
		const ERROR_FIELD_MODULE_REFERENCE_FILTER_EMPTY_COMPARATOR               = 'ERROR_FIELD_MODULE_REFERENCE_FILTER_EMPTY_COMPARATOR';
		const ERROR_FIELD_MODULE_REFERENCE_FILTER_EMPTY_FIELD_NAME               = 'ERROR_FIELD_MODULE_REFERENCE_FILTER_EMPTY_FIELD_NAME';
		const ERROR_FIELD_MODULE_REFERENCE_FILTER_EMPTY_SEQUENCE                 = 'ERROR_FIELD_MODULE_REFERENCE_FILTER_EMPTY_SEQUENCE';
		const ERROR_FIELD_MODULE_REFERENCE_FILTER_EMPTY_SOURCE_FIELD_MODULE_NAME = 'ERROR_FIELD_MODULE_REFERENCE_FILTER_EMPTY_SOURCE_FIELD_MODULE_NAME';
		const ERROR_FIELD_MODULE_REFERENCE_FILTER_EMPTY_SOURCE_FIELD_VALUE       = 'ERROR_FIELD_MODULE_REFERENCE_FILTER_EMPTY_SOURCE_FIELD_VALUE';
		const ERROR_FIELD_MODULE_REFERENCE_FILTER_INVALID_VALUE_TYPE             = 'ERROR_FIELD_MODULE_REFERENCE_FILTER_INVALID_VALUE_TYPE';

	}
