<?php

	class FieldException extends Exception {
		const ERROR_DUPLICATE_FIELD_NAME             = 'ERROR_DUPLICATE_FIELD_NAME';
		const ERROR_FIELD_COLUMN_NAME_TOO_LONG       = 'ERROR_FIELD_COLUMN_NAME_TOO_LONG';
		const ERROR_FIELD_EMPTY                      = 'ERROR_FIELD_EMPTY';
		const ERROR_FIELD_EMPTY_BLOCK_ID             = 'ERROR_FIELD_EMPTY_BLOCK_ID';
		const ERROR_FIELD_EMPTY_COLUMN_NAME          = 'ERROR_FIELD_EMPTY_COLUMN_NAME';
		const ERROR_FIELD_EMPTY_DATA_TYPE            = 'ERROR_FIELD_EMPTY_DATA_TYPE';
		const ERROR_FIELD_EMPTY_ENTITY_ID_COLUMN     = 'ERROR_FIELD_EMPTY_ENTITY_ID_COLUMN';
		const ERROR_FIELD_EMPTY_ENTITY_ID_FIELD_NAME = 'ERROR_FIELD_EMPTY_ENTITY_ID_FIELD_NAME';
		const ERROR_FIELD_EMPTY_GRID                 = 'ERROR_FIELD_EMPTY_GRID';
		const ERROR_FIELD_EMPTY_LABEL                = 'ERROR_FIELD_EMPTY_LABEL';
		const ERROR_FIELD_EMPTY_MANDATORY            = 'ERROR_FIELD_EMPTY_MANDATORY';
		const ERROR_FIELD_EMPTY_MODULE_NAME          = 'ERROR_FIELD_EMPTY_MODULE_NAME';
		const ERROR_FIELD_EMPTY_MODULE_REFERENCE     = 'ERROR_FIELD_EMPTY_MODULE_REFERENCE';
		const ERROR_FIELD_EMPTY_NAME                 = 'ERROR_FIELD_EMPTY_NAME';
		const ERROR_FIELD_EMPTY_PICKLIST             = 'ERROR_FIELD_EMPTY_PICKLIST';
		const ERROR_FIELD_EMPTY_PIPELINE             = 'ERROR_FIELD_EMPTY_PIPELINE';
		const ERROR_FIELD_EMPTY_TABLE_NAME           = 'ERROR_FIELD_EMPTY_TABLE_NAME';
		const ERROR_FIELD_EMPTY_UI_TYPE              = 'ERROR_FIELD_EMPTY_UI_TYPE';
		const ERROR_FIELD_NAME_TOO_LONG              = 'ERROR_FIELD_NAME_TOO_LONG';
		const ERROR_FIELD_INVALID_BLOCK_ID           = 'ERROR_FIELD_INVALID_BLOCK_ID';
		const ERROR_FIELD_INVALID_MODULE_NAME        = 'ERROR_FIELD_INVALID_MODULE_NAME';
		const ERROR_FIELD_INVALID_MODULE_REFERENCE   = 'ERROR_FIELD_INVALID_MODULE_REFERENCE';
		const ERROR_FIELD_INVALID_TABLE_NAME         = 'ERROR_FIELD_INVALID_TABLE_NAME';
		const ERROR_FIELD_TABLE_NAME_TOO_LONG        = 'ERROR_FIELD_TABLE_NAME_TOO_LONG';

	}
