<?php

	class FieldValidationException extends Exception {
		const ERROR_FIELD_VALIDATION_EMPTY               = 'ERROR_FIELD_VALIDATION_EMPTY';
		const ERROR_FIELD_VALIDATION_EMPTY_FIELD_NAME    = 'ERROR_FIELD_VALIDATION_EMPTY_FIELD_NAME';
		const ERROR_FIELD_VALIDATION_EMPTY_MODULE_NAME   = 'ERROR_FIELD_VALIDATION_EMPTY_MODULE_NAME';
		const ERROR_FIELD_VALIDATION_EMPTY_TABLE_NAME    = 'ERROR_FIELD_VALIDATION_EMPTY_TABLE_NAME';
		const ERROR_FIELD_VALIDATION_EMPTY_TYPE          = 'ERROR_FIELD_VALIDATION_EMPTY_TYPE';
		const ERROR_FIELD_VALIDATION_INVALID_FIELD_NAME  = 'ERROR_FIELD_VALIDATION_INVALID_FIELD_NAME';
		const ERROR_FIELD_VALIDATION_INVALID_MODULE_NAME = 'ERROR_FIELD_VALIDATION_INVALID_MODULE_NAME';

	}
