<?php

	class FieldDependencyException extends Exception {
		const ERROR_FIELD_DEPENDENCY_EMPTY                           = 'ERROR_FIELD_DEPENDENCY_EMPTY';
		const ERROR_FIELD_DEPENDENCY_EMPTY_MODULE_NAME               = 'ERROR_FIELD_DEPENDENCY_EMPTY_MODULE_NAME';
		const ERROR_FIELD_DEPENDENCY_EMPTY_SOURCE_FIELD_NAME         = 'ERROR_FIELD_DEPENDENCY_EMPTY_SOURCE_FIELD_NAME';
		const ERROR_FIELD_DEPENDENCY_EMPTY_TARGET_FIELD_NAME         = 'ERROR_FIELD_DEPENDENCY_EMPTY_TARGET_FIELD_NAME';
		const ERROR_FIELD_DEPENDENCY_EMPTY_TARGET_FIELD_VISIBILITY   = 'ERROR_FIELD_DEPENDENCY_EMPTY_TARGET_FIELD_VISIBILITY';
		const ERROR_FIELD_DEPENDENCY_INVALID_MODULE_NAME             = 'ERROR_FIELD_DEPENDENCY_INVALID_MODULE_NAME';
		const ERROR_FIELD_DEPENDENCY_INVALID_SOURCE_FIELD_NAME       = 'ERROR_FIELD_DEPENDENCY_INVALID_SOURCE_FIELD_NAME';
		const ERROR_FIELD_DEPENDENCY_INVALID_SOURCE_FIELD_UITYPE     = 'ERROR_FIELD_DEPENDENCY_INVALID_SOURCE_FIELD_UITYPE';
		const ERROR_FIELD_DEPENDENCY_INVALID_TARGET_FIELD_NAME       = 'ERROR_FIELD_DEPENDENCY_INVALID_TARGET_FIELD_NAME';
		const ERROR_FIELD_DEPENDENCY_INVALID_TARGET_FIELD_VISIBILITY = 'ERROR_FIELD_DEPENDENCY_INVALID_TARGET_FIELD_VISIBILITY';

	}
