<?php

	class FieldModuleReferenceException extends Exception {
		const ERROR_FIELD_MODULE_REFERENCE_EMPTY_FIELD_NAME               = 'ERROR_FIELD_MODULE_REFERENCE_EMPTY_FIELD_NAME';
		const ERROR_FIELD_MODULE_REFERENCE_EMPTY_MODULE_NAME              = 'ERROR_FIELD_MODULE_REFERENCE_EMPTY_MODULE_NAME';
		const ERROR_FIELD_MODULE_REFERENCE_EMPTY_REFERENCE                = 'ERROR_FIELD_MODULE_REFERENCE_EMPTY_REFERENCE';
		const ERROR_FIELD_MODULE_REFERENCE_EMPTY_REFERENCED_MODULE_NAME   = 'ERROR_FIELD_MODULE_REFERENCE_EMPTY_REFERENCED_MODULE_NAME';
		const ERROR_FIELD_MODULE_REFERENCE_INVALID_FIELD_NAME             = 'ERROR_FIELD_MODULE_REFERENCE_INVALID_FIELD_NAME';
		const ERROR_FIELD_MODULE_REFERENCE_INVALID_FILTER                 = 'ERROR_FIELD_MODULE_REFERENCE_INVALID_FILTER';
		const ERROR_FIELD_MODULE_REFERENCE_INVALID_MODULE_NAME            = 'ERROR_FIELD_MODULE_REFERENCE_INVALID_MODULE_NAME';
		const ERROR_FIELD_MODULE_REFERENCE_INVALID_REFERENCED_MODULE_NAME = 'ERROR_FIELD_MODULE_REFERENCE_INVALID_MODULE_NAME';
		const ERROR_FIELD_MODULE_REFERENCE_INVALID_RELATIONSHIP           = 'ERROR_FIELD_MODULE_REFERENCE_INVALID_RELATIONSHIP';

	}
