<?php

	class FilterGroupException extends Exception {
		const ERROR_FILTER_GROUP_EMPTY_FILTERS    = 'ERROR_FILTER_GROUP_EMPTY_FILTERS';
		const ERROR_FILTER_GROUP_EMPTY_ID         = 'ERROR_FILTER_GROUP_EMPTY_ID';
		const ERROR_FILTER_GROUP_ID_ALREADY_TAKEN = 'ERROR_FILTER_GROUP_ID_ALREADY_TAKEN';

	}
