<?php

	class FilterException extends Exception {
		const ERROR_FILTER_EMPTY_COMPARATOR       = 'ERROR_FILTER_EMPTY_COMPARATOR';
		const ERROR_FILTER_EMPTY_FIELD_NAME       = 'ERROR_FILTER_EMPTY_FIELD_NAME';
		const ERROR_FILTER_EMPTY_GROUP_ID         = 'ERROR_FILTER_EMPTY_GROUP_ID';
		const ERROR_FILTER_EMPTY_LABEL            = 'ERROR_FILTER_EMPTY_LABEL';
		const ERROR_FILTER_EMPTY_MODULE_NAME      = 'ERROR_FILTER_EMPTY_MODULE_NAME';
		const ERROR_FILTER_EMPTY_SEQUENCE         = 'ERROR_FILTER_EMPTY_SEQUENCE';
		const ERROR_FILTER_INVALID_FIELD_NAME     = 'ERROR_FILTER_INVALID_FIELD_NAME';
		const ERROR_FILTER_INVALID_FILTER         = 'ERROR_FILTER_INVALID_FILTER';
		const ERROR_FILTER_INVALID_MODULE_NAME    = 'ERROR_FILTER_INVALID_MODULE_NAME';
		const ERROR_FILTER_SEQUENCE_ALREADY_TAKEN = 'ERROR_FILTER_SEQUENCE_ALREADY_TAKEN';

	}
