<?php

	class GridViewException extends Exception {
		const ERROR_GRID_VIEW_EMPTY_BOX_LABEL   = 'ERROR_GRID_VIEW_EMPTY_BOX_LABEL';
		const ERROR_GRID_VIEW_EMPTY_BOX_NAME    = 'ERROR_GRID_VIEW_EMPTY_BOX_NAME';
		const ERROR_GRID_VIEW_EMPTY_NAME        = 'ERROR_GRID_VIEW_EMPTY_NAME';
		const ERROR_GRID_VIEW_EMPTY_MODULE_NAME = 'ERROR_GRID_VIEW_EMPTY_MODULE_NAME';
	}
