<?php

	class GridException extends Exception {
		const ERROR_GRID_EMPTY_NAME                     = 'ERROR_GRID_EMPTY_NAME';
		const ERROR_GRID_EMPTY_FIELDS                   = 'ERROR_GRID_EMPTY_FIELDS';
		const ERROR_GRID_EMPTY_MODULE_NAME              = 'ERROR_GRID_EMPTY_MODULE_NAME';
		const ERROR_GRID_INVALID_FIELD                  = 'ERROR_GRID_INVALID_FIELD';
		const ERROR_GRID_INVALID_FIELD_NAME             = 'ERROR_GRID_INVALID_FIELD_NAME';
		const ERROR_GRID_INVALID_GRID                   = 'ERROR_GRID_INVALID_GRID';
		const ERROR_GRID_INVALID_MODULE_NAME            = 'ERROR_GRID_INVALID_MODULE_NAME';
		const ERROR_GRID_INVALID_MODULE_REFERENCE       = 'ERROR_GRID_INVALID_MODULE_REFERENCE';
		const ERROR_GRID_INVALID_REFERENCED_MODULE_NAME = 'ERROR_GRID_INVALID_REFERENCED_MODULE_NAME';
		const ERROR_GRID_NOT_FOUND                      = 'ERROR_GRID_NOT_FOUND';

	}
