<?php
	class HowToUseException extends Exception {
		const ERROR_VIEW_EMPTY_MASTER_VIEW         = 'ERROR_VIEW_EMPTY_MASTER_VIEW';
		const ERROR_VIEW_EMPTY_INDEX_VIEW_NAME     = 'ERROR_VIEW_EMPTY_DEFAULT_VIEW_MODULE';
		const ERROR_VIEW_EMPTY_HOW_USE_NAME        = 'ERROR_VIEW_EMPTY_HOW_USE_NAME';
		const ERROR_VIEW_EMPTY_DEFAULT_VIEW_MODULE = 'ERROR_VIEW_EMPTY_DEFAULT_VIEW_MODULE';
		const ERROR_VIEW_EMPTY_HOW_USE_MODULE      = 'ERROR_VIEW_EMPTY_HOW_USE_MODULE';
	}
