<?php

	class KanbanViewException extends Exception {
		const ERROR_KANABAN_VIEW_EMPTY_APPLICATION_CODE = 'ERROR_KANABAN_VIEW_EMPTY_APPLICATION_CODE';
		const ERROR_KANABAN_VIEW_EMPTY_BACKGROUND_COLOR = 'ERROR_KANABAN_VIEW_EMPTY_BACKGROUND_COLOR';
		const ERROR_KANABAN_VIEW_EMPTY_FIELD_ID         = 'ERROR_KANABAN_VIEW_EMPTY_FIELD_ID';
		const ERROR_KANABAN_VIEW_EMPTY_FIELD_NAME       = 'ERROR_KANABAN_VIEW_EMPTY_FIELD_NAME';
		const ERROR_KANABAN_VIEW_EMPTY_ID               = 'ERROR_KANABAN_VIEW_EMPTY_ID';
		const ERROR_KANABAN_VIEW_EMPTY_LABEL            = 'ERROR_KANABAN_VIEW_EMPTY_LABEL';
		const ERROR_KANABAN_VIEW_EMPTY_MODULE_NAME      = 'ERROR_KANABAN_VIEW_EMPTY_MODULE_NAME';
		const ERROR_KANABAN_VIEW_EMPTY_MODULE_TAB_ID    = 'ERROR_KANABAN_VIEW_EMPTY_MODULE_TAB_ID';
		const ERROR_KANABAN_VIEW_EMPTY_PICK_ID          = 'ERROR_KANABAN_VIEW_EMPTY_PICK_ID';
	}
