<?php

	class ModuleProfileException extends Exception {
		const ERROR_MODULE_PROFILE_EMPTY                = 'ERROR_MODULE_PROFILE_EMPTY';
		const ERROR_MODULE_PROFILE_EMPTY_MODULE_NAME    = 'ERROR_MODULE_PROFILE_EMPTY_MODULE_NAME';
		const ERROR_MODULE_PROFILE_EMPTY_PROFILE_NAME   = 'ERROR_MODULE_PROFILE_EMPTY_PROFILE_NAME';
		const ERROR_MODULE_PROFILE_INVALID_MODULE_NAME  = 'ERROR_MODULE_PROFILE_INVALID_MODULE_NAME';
		const ERROR_MODULE_PROFILE_INVALID_PROFILE_NAME = 'ERROR_MODULE_PROFILE_INVALID_PROFILE_NAME';

	}
