<?php

	class ModuleRelationshipException extends Exception {
		const ERROR_MODULE_RELATIONSHIP_EMPTY                       = 'ERROR_MODULE_RELATIONSHIP_EMPTY';
		const ERROR_MODULE_RELATIONSHIP_EMPTY_FUNCTION              = 'ERROR_MODULE_RELATIONSHIP_EMPTY_FUNCTION';
		const ERROR_MODULE_RELATIONSHIP_EMPTY_LABEL                 = 'ERROR_MODULE_RELATIONSHIP_EMPTY_LABEL';
		const ERROR_MODULE_RELATIONSHIP_EMPTY_MODULE_NAME           = 'ERROR_MODULE_RELATIONSHIP_EMPTY_MODULE_NAME';
		const ERROR_MODULE_RELATIONSHIP_EMPTY_RELATED_MODULE_NAME   = 'ERROR_MODULE_RELATIONSHIP_EMPTY_RELATED_MODULE_NAME';
		const ERROR_MODULE_RELATIONSHIP_INVALID_ACTION              = 'ERROR_MODULE_RELATIONSHIP_INVALID_ACTION';
		const ERROR_MODULE_RELATIONSHIP_INVALID_ACTIONS             = 'ERROR_MODULE_RELATIONSHIP_INVALID_ACTIONS';
		const ERROR_MODULE_RELATIONSHIP_INVALID_MODULE_NAME         = 'ERROR_MODULE_RELATIONSHIP_INVALID_MODULE_NAME';
		const ERROR_MODULE_RELATIONSHIP_INVALID_RELATED_MODULE_NAME = 'ERROR_MODULE_RELATIONSHIP_INVALID_RELATED_MODULE_NAME';

	}
