<?php

	class ModuleException extends Exception {
		const ERROR_MODULE_DUPLICATE_NAME                 = 'ERROR_MODULE_DUPLICATE_NAME';
		const ERROR_MODULE_EMPTY                          = 'ERROR_MODULE_EMPTY';
		const ERROR_MODULE_EMPTY_BACKGROUND_TASK          = 'ERROR_MODULE_EMPTY_BACKGROUND_TASK';
		const ERROR_MODULE_EMPTY_BLOCK                    = 'ERROR_MODULE_EMPTY_BLOCK';
		const ERROR_MODULE_EMPTY_BLOCKS                   = 'ERROR_MODULE_EMPTY_BLOCKS';
		const ERROR_MODULE_EMPTY_BUTTON                   = 'ERROR_MODULE_EMPTY_BUTTON';
		const ERROR_MODULE_EMPTY_CALCULATED_ELEMENT       = 'ERROR_MODULE_EMPTY_CALCULATED_ELEMENT';
		const ERROR_MODULE_EMPTY_CALCULATION_SYSTEM       = 'ERROR_MODULE_EMPTY_CALCULATION_SYSTEM';
		const ERROR_MODULE_EMPTY_CALENDAR_VIEW            = 'ERROR_MODULE_EMPTY_CALENDAR_VIEW';
		const ERROR_MODULE_EMPTY_CHART                    = 'ERROR_MODULE_EMPTY_CHART';
		const ERROR_MODULE_EMPTY_ENTITY_PREFIX            = 'ERROR_MODULE_EMPTY_ENTITY_PREFIX';
		const ERROR_MODULE_EMPTY_ENTITY_SEQUENCE          = 'ERROR_MODULE_EMPTY_ENTITY_SEQUENCE';
		const ERROR_MODULE_EMPTY_KANBAN_VIEW              = 'ERROR_MODULE_EMPTY_KANBAN_VIEW';
		const ERROR_MODULE_EMPTY_LABEL                    = 'ERROR_MODULE_EMPTY_LABEL';
		const ERROR_MODULE_EMPTY_NAME                     = 'ERROR_MODULE_EMPTY_NAME';
		const ERROR_MODULE_EMPTY_NOTICATION               = 'ERROR_MODULE_EMPTY_NOTICATION';
		const ERROR_MODULE_EMPTY_PRESENCE                 = 'ERROR_MODULE_EMPTY_PRESENCE';
		const ERROR_MODULE_EMPTY_REPORT                   = 'ERROR_MODULE_EMPTY_REPORT';
		const ERROR_MODULE_EMPTY_SCORING_BOX              = 'ERROR_MODULE_EMPTY_SCORING_BOX';
		const ERROR_MODULE_EMPTY_REPORT_TEMPLATE          = 'ERROR_MODULE_EMPTY_REPORT_TEMPLATE';
		const ERROR_MODULE_EMPTY_TYPE                     = 'ERROR_MODULE_EMPTY_TYPE';
		const ERROR_MODULE_EMPTY_VIEW                     = 'ERROR_MODULE_EMPTY_VIEW';
		const ERROR_MODULE_EMPTY_VIEWS                    = 'ERROR_MODULE_EMPTY_VIEWS';
		const ERROR_MODULE_INVALID_BACKGROUND_TASK        = 'ERROR_MODULE_INVALID_BACKGROUND_TASK';
		const ERROR_MODULE_INVALID_BLOCK                  = 'ERROR_MODULE_INVALID_BLOCK';
		const ERROR_MODULE_INVALID_BLOCKS                 = 'ERROR_MODULE_INVALID_BLOCKS';
		const ERROR_MODULE_INVALID_BUTTON                 = 'ERROR_MODULE_INVALID_BUTTON';
		const ERROR_MODULE_INVALID_BUTTONS                = 'ERROR_MODULE_INVALID_BUTTONS';
		const ERROR_MODULE_INVALID_CALCULATED_ELEMENT     = 'ERROR_MODULE_INVALID_CALCULATED_ELEMENT';
		const ERROR_MODULE_INVALID_CALCULATION_SYSTEM     = 'ERROR_MODULE_INVALID_CALCULATION_SYSTEM';
		const ERROR_MODULE_INVALID_CALENDAR_VIEW          = 'ERROR_MODULE_INVALID_CALENDAR_VIEW';
		const ERROR_MODULE_INVALID_CALENDAR_VIEWS         = 'ERROR_MODULE_INVALID_CALENDAR_VIEWS';
		const ERROR_MODULE_INVALID_CHART                  = 'ERROR_MODULE_INVALID_CHART';
		const ERROR_MODULE_INVALID_CHARTS                 = 'ERROR_MODULE_INVALID_CHARTS';
		const ERROR_MODULE_INVALID_EDITABLE_FIELDS_BUTTON = 'ERROR_MODULE_INVALID_EDITABLE_FIELDS_BUTTON';
		const ERROR_MODULE_INVALID_GRID_VIEW              = 'ERROR_MODULE_INVALID_GRID_VIEW';
		const ERROR_MODULE_INVALID_HOW_TO_USE             = 'ERROR_MODULE_INVALID_HOW_TO_USE';
		const ERROR_MODULE_INVALID_CODE_FIELD             = 'ERROR_MODULE_INVALID_CODE_FIELD';
		const ERROR_MODULE_INVALID_ENTITY_IDENTIFIER      = 'ERROR_MODULE_INVALID_ENTITY_IDENTIFIER';
		const ERROR_MODULE_INVALID_ENTITY_SEQUENCE        = 'ERROR_MODULE_INVALID_ENTITY_SEQUENCE';
		const ERROR_MODULE_INVALID_KANBAN_VIEW            = 'ERROR_MODULE_INVALID_KANBAN_VIEW';
		const ERROR_MODULE_INVALID_NAME                   = 'ERROR_MODULE_INVALID_NAME';
		const ERROR_MODULE_INVALID_NOTIFICATION           = 'ERROR_MODULE_INVALID_NOTIFICATION';
		const ERROR_MODULE_INVALID_PICKLIST_RELATIONSHIP  = 'ERROR_MODULE_INVALID_PICKLIST_RELATIONSHIP';
		const ERROR_MODULE_INVALID_REPORT                 = 'ERROR_MODULE_INVALID_REPORT';
		const ERROR_MODULE_INVALID_REPORT_TEMPLATE        = 'ERROR_MODULE_INVALID_REPORT_TEMPLATE';
		const ERROR_MODULE_INVALID_REPORT_TEMPLATES       = 'ERROR_MODULE_INVALID_REPORT_TEMPLATES';
		const ERROR_MODULE_INVALID_REPORTS                = 'ERROR_MODULE_INVALID_REPORTS';
		const ERROR_MODULE_INVALID_SCORING_BOX            = 'ERROR_MODULE_INVALID_SCORING_BOX';
		const ERROR_MODULE_INVALID_SEQUENCE               = 'ERROR_MODULE_INVALID_SEQUENCE';
		const ERROR_MODULE_INVALID_VIEW                   = 'ERROR_MODULE_INVALID_VIEW';
		const ERROR_MODULE_INVALID_VIEWS                  = 'ERROR_MODULE_INVALID_VIEWS';

	}
