<?php

	class NotificationException extends Exception {
		const ERROR_NOTIFICATION_EMPTY_ACTION          = 'ERROR_NOTIFICATION_EMPTY_ACTION';
		const ERROR_NOTIFICATION_EMPTY_CONTENTS        = 'ERROR_NOTIFICATION_EMPTY_CONTENTS';
		const ERROR_NOTIFICATION_EMPTY_EVENT           = 'ERROR_NOTIFICATION_EMPTY_EVENT';
		const ERROR_NOTIFICATION_EMPTY_EVENT_PARAMETER = 'ERROR_NOTIFICATION_EMPTY_EVENT_PARAMETER';
		const ERROR_NOTIFICATION_EMPTY_FROM            = 'ERROR_NOTIFICATION_EMPTY_EVENT_FROM';
		const ERROR_NOTIFICATION_EMPTY_MODULE_NAMES    = 'ERROR_NOTIFICATION_EMPTY_MODULE_NAMES';
		const ERROR_NOTIFICATION_EMPTY_NAME            = 'ERROR_NOTIFICATION_EMPTY_NAME';
		const ERROR_NOTIFICATION_EMPTY_STATUS          = 'ERROR_NOTIFICATION_EMPTY_STATUS';
		const ERROR_NOTIFICATION_EMPTY_STYLE           = 'ERROR_NOTIFICATION_EMPTY_STYLE';
		const ERROR_NOTIFICATION_EMPTY_TYPE            = 'ERROR_NOTIFICATION_EMPTY_TYPE';
		const ERROR_NOTIFICATION_EMPTY_USERS_NAMES     = 'ERROR_NOTIFICATION_EMPTY_USERS_NAMES';
		const ERROR_NOTIFICATION_INVALID_MODULE_NAME   = 'ERROR_NOTIFICATION_INVALID_MODULE_NAME';
		const ERROR_NOTIFICATION_INVALID_USERS_NAME    = 'ERROR_NOTIFICATION_INVALID_USERS_NAME';

	}
