<?php

	class PaymentException extends Exception {
		const ERROR_PAYMENT_EMPTY_DUE_DATE           = 'ERROR_PAYMENT_EMPTY_DUE_DATE';
		const ERROR_PAYMENT_EMPTY_ID                 = 'ERROR_PAYMENT_EMPTY_ID';
		const ERROR_PAYMENT_EMPTY_INSTANCE_CODE      = 'ERROR_PAYMENT_EMPTY_INSTANCE_CODE';
		const ERROR_PAYMENT_EMPTY_PRODUCT_ID         = 'ERROR_PAYMENT_EMPTY_PRODUCT_ID';
		const ERROR_PAYMENT_EMPTY_PRODUCT_NAME       = 'ERROR_PAYMENT_EMPTY_PRODUCT_NAME';
		const ERROR_PAYMENT_EMPTY_SERVICE_END_DATE   = 'ERROR_PAYMENT_EMPTY_SERVICE_END_DATE';
		const ERROR_PAYMENT_EMPTY_SERVICE_START_DATE = 'ERROR_PAYMENT_EMPTY_SERVICE_START_DATE';
		const ERROR_PAYMENT_EMPTY_STATUS             = 'ERROR_PAYMENT_EMPTY_STATUS';
		const ERROR_PAYMENT_EMPTY_SUB_TOTAL          = 'ERROR_PAYMENT_EMPTY_SUB_TOTAL';
		const ERROR_PAYMENT_EMPTY_TYPE               = 'ERROR_PAYMENT_EMPTY_TYPE';

	}
