<?php

	class PicklistValueException extends Exception {
		const ERROR_PICKLIST_VALUE_EMPTY_PRESENCE   = 'ERROR_PICKLIST_VALUE_EMPTY_PRESENCE';
		const ERROR_PICKLIST_VALUE_INVALID_PRESENCE = 'ERROR_PICKLIST_VALUE_INVALID_PRESENCE';

	}
