<?php

	class PicklistRelationshipException extends Exception {
		const ERROR_PICKLIST_RELATIONSHIP_DAUGHTER_IDS_EMPTY        = 'ERROR_PICKLIST_RELATIONSHIP_DAUGHTER_IDS_NAME';
		const ERROR_PICKLIST_RELATIONSHIP_DAUGHTER_NAME_EMPTY       = 'ERROR_PICKLIST_RELATIONSHIP_DAUGHTER_NAME_NAME';
		const ERROR_PICKLIST_RELATIONSHIP_MODULE_NAME_EMPTY         = 'ERROR_PICKLIST_RELATIONSHIP_MODULE_NAME_EMPTY';
		const ERROR_PICKLIST_RELATIONSHIP_MOTHER_IDS_EMPTY          = 'ERROR_PICKLIST_RELATIONSHIP_MOTHER_IDS_EMPTY';
		const ERROR_PICKLIST_RELATIONSHIP_MOTHER_NAME_EMPTY         = 'ERROR_PICKLIST_RELATIONSHIP_MOTHER_NAME_EMPTY';
		const ERROR_PICKLIST_RELATIONSHIP_RELATIONSHIP_MASTER_EMPTY = 'ERROR_PICKLIST_RELATIONSHIP_RELATIONSHIP_MASTER_EMPTY';
		const ERROR_PICKLIST_RELATIONSHIP_RELATIONSHIP_NAME_EMPTY   = 'ERROR_PICKLIST_RELATIONSHIP_RELATIONSHIP_NAME_EMPTY';
		const ERROR_PICKLIST_RELATIONSHIP_RELATIONSHIP_VALUES_EMPTY = 'ERROR_PICKLIST_RELATIONSHIP_RELATIONSHIP_VALUES_EMPTY';
	}
