<?php

	class PicklistException extends Exception {
		const ERROR_PICKLIST_DUPLICATE_LABEL = 'ERROR_PICKLIST_DUPLICATE_LABEL';
		const ERROR_PICKLIST_DUPLICATE_NAME  = 'ERROR_PICKLIST_DUPLICATE_NAME';
		const ERROR_PICKLIST_EMPTY           = 'ERROR_PICKLIST_EMPTY';
		const ERROR_PICKLIST_EMPTY_LABEL     = 'ERROR_PICKLIST_EMPTY_LABEL';
		const ERROR_PICKLIST_EMPTY_NAME      = 'ERROR_PICKLIST_EMPTY_NAME';
		const ERROR_PICKLIST_EMPTY_VALUES    = 'ERROR_PICKLIST_EMPTY_VALUES';
		const ERROR_PICKLIST_INVALID_VALUE   = 'ERROR_PICKLIST_INVALID_VALUE';

	}
