<?php

	class PipelineException extends Exception {
		const ERROR_PIPELINE_EMPTY_FIELD_NAME  = 'ERROR_PIPELINE_EMPTY_FIELD_NAME';
		const ERROR_PIPELINE_EMPTY_MODULE_NAME = 'ERROR_PIPELINE_EMPTY_MODULE_NAME';
		const ERROR_PIPELINE_EMPTY_VALUES      = 'ERROR_PIPELINE_EMPTY_VALUES';

	}
