<?php

	class PlatformException extends Exception {
		const ERROR_PLATFORM_APPLICATION_NOT_FOUND         = 'ERROR_PLATFORM_APPLICATION_NOT_FOUND';
		const ERROR_PLATFORM_EMPTY_APPLICATIONS            = 'ERROR_PLATFORM_EMPTY_APPLICATIONS';
		const ERROR_PLATFORM_EMPTY_CODE                    = 'ERROR_PLATFORM_EMPTY_CODE';
		const ERROR_PLATFORM_EMPTY_CONFIGURATION           = 'ERROR_PLATFORM_EMPTY_CONFIGURATION';
		const ERROR_PLATFORM_EMPTY_INSTANCE_CODE           = 'ERROR_PLATFORM_EMPTY_INSTANCE_CODE';
		const ERROR_PLATFORM_EMPTY_MODULES                 = 'ERROR_PLATFORM_EMPTY_MODULES';
		const ERROR_PLATFORM_EMPTY_HTTP_DATABASE_HOST_NAME = 'ERROR_PLATFORM_EMPTY_HTTP_DATABASE_HOST_NAME';
		const ERROR_PLATFORM_EMPTY_STOCK_INSTANCES         = 'ERROR_PLATFORM_EMPTY_STOCK_INSTANCES';
		const ERROR_PLATFORM_INVALID_BILLING_PLAN          = 'ERROR_PLATFORM_INVALID_BILLING_PLAN';
		const ERROR_PLATFORM_INVALID_INSTANCE_CODE         = 'ERROR_PLATFORM_INVALID_INSTANCE_CODE';
		const ERROR_PLATFORM_INVALID_SELECTED_APPLICATION  = 'ERROR_PLATFORM_INVALID_SELECTED_APPLICATION';
		const ERROR_PLATFORM_UNABLE_TO_UPDATE_INSTANCES    = 'ERROR_PLATFORM_UNABLE_TO_UPDATE_INSTANCES';
		const ERROR_PLATFORM_UNELIGIBLE_FOR_FREE_PLAN      = 'ERROR_PLATFORM_UNELIGIBLE_FOR_FREE_PLAN';

	}
