<?php

	class PlatformInstanceException extends Exception {
		const ERROR_INSTANCE_EMPTY                        = 'ERROR_INSTANCE_EMPTY';
		const ERROR_INSTANCE_EMPTY_ADMINISTRATOR          = 'ERROR_INSTANCE_EMPTY_ADMINISTRATOR';
		const ERROR_INSTANCE_EMPTY_BILLING_PLAN           = 'ERROR_INSTANCE_EMPTY_BILLING_PLAN';
		const ERROR_INSTANCE_EMPTY_CODE                   = 'ERROR_INSTANCE_EMPTY_CODE';
		const ERROR_INSTANCE_EMPTY_MODULES                = 'ERROR_INSTANCE_EMPTY_MODULES';
		const ERROR_INSTANCE_EMPTY_NAME                   = 'ERROR_INSTANCE_EMPTY_NAME';
		const ERROR_INSTANCE_INVALID                      = 'ERROR_INSTANCE_INVALID';
		const ERROR_INSTANCE_INVALID_APPLICATIONS         = 'ERROR_INSTANCE_INVALID_APPLICATIONS';
		const ERROR_INSTANCE_INVALID_APPLICATION          = 'ERROR_INSTANCE_INVALID_APPLICATION';
		const ERROR_INSTANCE_INVALID_MODULE               = 'ERROR_INSTANCE_INVALID_MODULE';
		const ERROR_INSTANCE_INVALID_MODULE_RELATIONSHIP  = 'ERROR_INSTANCE_INVALID_MODULE_RELATIONSHIP';
		const ERROR_INSTANCE_INVALID_MODULE_RELATIONSHIPS = 'ERROR_INSTANCE_INVALID_MODULE_RELATIONSHIPS';
		const ERROR_INSTANCE_INVALID_MODULES              = 'ERROR_INSTANCE_INVALID_MODULES';
		const ERROR_INSTANCE_INVALID_USER                 = 'ERROR_INSTANCE_INVALID_USER';
		const ERROR_INSTANCE_INVALID_USERS                = 'ERROR_INSTANCE_INVALID_USERS';

	}
