<?php

	class PlatformBillingPlanException extends Exception {
		const ERROR_BILLING_PLAN_DUPLICATED_NAME          = 'ERROR_BILLING_PLAN_DUPLICATED_NAME';
		const ERROR_BILLING_PLAN_EMPTY_DESCRIPTION        = 'ERROR_BILLING_PLAN_EMPTY_DESCRIPTION';
		const ERROR_BILLING_PLAN_EMPTY_NAME               = 'ERROR_BILLING_PLAN_EMPTY_NAME';
		const ERROR_BILLING_PLAN_EMPTY_PRODUCT            = 'ERROR_BILLING_PLAN_EMPTY_PRODUCT';
		const ERROR_BILLING_PLAN_EMPTY_STATUS             = 'ERROR_BILLING_PLAN_EMPTY_STATUS';
		const ERROR_BILLING_PLAN_EMPTY_TOTAL_APPLICATIONS = 'ERROR_BILLING_PLAN_EMPTY_TOTAL_APPLICATIONS';
		const ERROR_BILLING_PLAN_EMPTY_TOTAL_DISK_SPACE   = 'ERROR_BILLING_PLAN_EMPTY_TOTAL_DISK_SPACE';
		const ERROR_BILLING_PLAN_EMPTY_TOTAL_USERS        = 'ERROR_BILLING_PLAN_EMPTY_TOTAL_USERS';
		const ERROR_BILLING_PLAN_IN_USE                   = 'ERROR_BILLING_PLAN_IN_USE';
		const ERROR_BILLING_PLAN_INVALID                  = 'ERROR_BILLING_PLAN_INVALID';

	}
