<?php

	class PlatformFreeBillingPlanLimitException extends Exception {
		const ERROR_FREE_BILLING_PLAN_LIMIT_EMPTY_MODULE_NAME   = 'ERROR_FREE_BILLING_PLAN_LIMIT_EMPTY_MODULE_NAME';
		const ERROR_FREE_BILLING_PLAN_LIMIT_EMPTY_MAX_RECORDS   = 'ERROR_FREE_BILLING_PLAN_LIMIT_EMPTY_MAX_RECORDS';
		const ERROR_FREE_BILLING_PLAN_LIMIT_INVALID             = 'ERROR_FREE_BILLING_PLAN_LIMIT_INVALID';
		const ERROR_FREE_BILLING_PLAN_LIMIT_INVALID_MODULE_NAME = 'ERROR_FREE_BILLING_PLAN_LIMIT_INVALID_MODULE_NAME';

	}
