<?php

	class PricebookException extends Exception {
		const ERROR_PRICEBOOK_DUPLICATE_NAME          = 'ERROR_PRICEBOOK_DUPLICATE_NAME';
		const ERROR_PRICEBOOK_EMPTY                   = 'ERROR_PRICEBOOK_EMPTY';
		const ERROR_PRICEBOOK_EMPTY_CONDITION_GROUP   = 'ERROR_PRICEBOOK_EMPTY_CONDITION_GROUP';
		const ERROR_PRICEBOOK_EMPTY_DEFAULT           = 'ERROR_PRICEBOOK_EMPTY_DEFAULT';
		const ERROR_PRICEBOOK_EMPTY_ID                = 'ERROR_PRICEBOOK_EMPTY_ID';
		const ERROR_PRICEBOOK_EMPTY_MULTIPLIER        = 'ERROR_PRICEBOOK_EMPTY_MULTIPLIER';
		const ERROR_PRICEBOOK_EMPTY_NAME              = 'ERROR_PRICEBOOK_EMPTY_NAME';
		const ERROR_PRICEBOOK_INVALID_CONDITION_GROUP = 'ERROR_PRICEBOOK_INVALID_CONDITION_GROUP';

	}
