<?php

	class PricebookConditionGroupException extends Exception {
		const ERROR_PRICEBOOK_CONDITION_GROUP_EMPTY_ID          = 'ERROR_PRICEBOOK_CONDITION_GROUP_EMPTY_ID';
		const ERROR_PRICEBOOK_CONDITION_GROUP_EMPTY_CONDITION   = 'ERROR_PRICEBOOK_CONDITION_GROUP_EMPTY_CONDITION';
		const ERROR_PRICEBOOK_CONDITION_GROUP_EMPTY_CONDITIONS  = 'ERROR_PRICEBOOK_CONDITION_GROUP_EMPTY_CONDITIONS';
		const ERROR_PRICEBOOK_CONDITION_GROUP_EMPTY_OPERATOR    = 'ERROR_PRICEBOOK_CONDITION_GROUP_EMPTY_OPERATOR';
		const ERROR_PRICEBOOK_CONDITION_GROUP_INVALID_CONDITION = 'ERROR_PRICEBOOK_CONDITION_GROUP_INVALID_CONDITION';

	}
