<?php

	class PricebookConditionException extends Exception {
		const ERROR_PRICEBOOK_CONDITION_EMPTY_ID            = 'ERROR_PRICEBOOK_CONDITION_EMPTY_ID';
		const ERROR_PRICEBOOK_CONDITION_EMPTY_COMPARATOR    = 'ERROR_PRICEBOOK_CONDITION_EMPTY_COMPARATOR';
		const ERROR_PRICEBOOK_CONDITION_EMPTY_GROUP_ID      = 'ERROR_PRICEBOOK_CONDITION_EMPTY_GROUP_ID';
		const ERROR_PRICEBOOK_CONDITION_EMPTY_OPERATOR      = 'ERROR_PRICEBOOK_CONDITION_EMPTY_OPERATOR';
		const ERROR_PRICEBOOK_CONDITION_EMPTY_PRICEBOOK_ID  = 'ERROR_PRICEBOOK_CONDITION_EMPTY_PRICEBOOK_ID';
		const ERROR_PRICEBOOK_CONDITION_EMPTY_VALUE         = 'ERROR_PRICEBOOK_CONDITION_EMPTY_VALUE';
		const ERROR_PRICEBOOK_CONDITION_EMPTY_VARIABLE_NAME = 'ERROR_PRICEBOOK_CONDITION_EMPTY_VARIABLE_NAME';
		const ERROR_PRICEBOOK_CONDITION_EMPTY_VARIABLE_TYPE = 'ERROR_PRICEBOOK_CONDITION_EMPTY_VARIABLE_TYPE';

	}
