<?php

	class ProductException extends Exception {
		const ERROR_PRODUCT_DUPLICATE_NAME = 'ERROR_PRODUCT_DUPLICATE_NAME';
		const ERROR_PRODUCT_EMPTY          = 'ERROR_PRODUCT_EMPTY';
		const ERROR_PRODUCT_EMPTY_NAME     = 'ERROR_PRODUCT_EMPTY_NAME';
		const ERROR_PRODUCT_EMPTY_PRICE    = 'ERROR_PRODUCT_EMPTY_PRICE';
		const ERROR_PRODUCT_EMPTY_TYPE     = 'ERROR_PRODUCT_EMPTY_TYPE';

	}
