<?php

	class ProfileException extends Exception {
		const ERROR_PROFILE_DUPLICATE_NAME         = 'ERROR_PROFILE_DUPLICATE_NAME';
		const ERROR_PROFILE_EMPTY                  = 'ERROR_PROFILE_EMPTY';
		const ERROR_PROFILE_EMPTY_FIELD_PROFILE    = 'ERROR_PROFILE_EMPTY_FIELD_PROFILE';
		const ERROR_PROFILE_EMPTY_MODULE_PROFILE   = 'ERROR_PROFILE_EMPTY_MODULE_PROFILE';
		const ERROR_PROFILE_EMPTY_PROFILE          = 'ERROR_PROFILE_EMPTY_PROFILE';
		const ERROR_PROFILE_EMPTY_PROFILE_NAME     = 'ERROR_PROFILE_EMPTY_PROFILE_NAME';
		const ERROR_PROFILE_EMPTY_VIEW_PROFILE     = 'ERROR_PROFILE_EMPTY_VIEW_PROFILE';
		const ERROR_PROFILE_INVALID_FIELD_PROFILE  = 'ERROR_PROFILE_INVALID_FIELD_PROFILE';
		const ERROR_PROFILE_INVALID_MODULE_PROFILE = 'ERROR_PROFILE_INVALID_MODULE_PROFILE';
		const ERROR_PROFILE_INVALID_VIEW_PROFILE   = 'ERROR_PROFILE_INVALID_VIEW_PROFILE';

	}
