<?php

	class ReportSharingEntityException extends Exception {
		const ERROR_REPORT_SHARING_ENTITY_EMPTY_ID   = 'ERROR_REPORT_SHARING_ENTITY_EMPTY_ID';
		const ERROR_REPORT_SHARING_ENTITY_EMPTY_TYPE = 'ERROR_REPORT_SHARING_ENTITY_EMPTY_TYPE';

	}
