<?php

	class ReportColumnException extends Exception {
		const ERROR_REPORT_COLUMN_EMPTY_COLUMN_NAME   = 'ERROR_REPORT_COLUMN_EMPTY_COLUMN_NAME';
		const ERROR_REPORT_COLUMN_EMPTY_DATA_TYPE     = 'ERROR_REPORT_COLUMN_EMPTY_DATA_TYPE';
		const ERROR_REPORT_COLUMN_EMPTY_FIELD_NAME    = 'ERROR_REPORT_COLUMN_EMPTY_FIELD_NAME';
		const ERROR_REPORT_COLUMN_EMPTY_LABEL         = 'ERROR_REPORT_COLUMN_EMPTY_LABEL';
		const ERROR_REPORT_COLUMN_EMPTY_MODULE_NAME   = 'ERROR_REPORT_COLUMN_EMPTY_MODULE_NAME';
		const ERROR_REPORT_COLUMN_EMPTY_SEQUENCE      = 'ERROR_REPORT_COLUMN_EMPTY_SEQUENCE';
		const ERROR_REPORT_COLUMN_EMPTY_TABLE_NAME    = 'ERROR_REPORT_COLUMN_EMPTY_TABLE_NAME';
		const ERROR_REPORT_COLUMN_EMPTY_REPORT_ID     = 'ERROR_REPORT_COLUMN_EMPTY_REPORT_ID';
		const ERROR_REPORT_COLUMN_INVALID_COLUMN_NAME = 'ERROR_REPORT_COLUMN_INVALID_COLUMN_NAME';
		const ERROR_REPORT_COLUMN_INVALID_FIELD_NAME  = 'ERROR_REPORT_COLUMN_INVALID_FIELD_NAME';
		const ERROR_REPORT_COLUMN_INVALID_MODULE_NAME = 'ERROR_REPORT_COLUMN_INVALID_MODULE_NAME';
		const ERROR_REPORT_COLUMN_INVALID_TABLE_NAME  = 'ERROR_REPORT_COLUMN_INVALID_TABLE_NAME';

	}
