<?php

	class ReportAdvancedFilterGroupException extends Exception {
		const ERROR_REPORT_ADVANCED_FILTER_GROUP_EMPTY_FILTERS          = 'ERROR_REPORT_ADVANCED_FILTER_GROUP_EMPTY_FILTERS';
		const ERROR_REPORT_ADVANCED_FILTER_GROUP_EMPTY_REPORT_ID        = 'ERROR_REPORT_ADVANCED_FILTER_GROUP_EMPTY_REPORT_ID';
		const ERROR_REPORT_ADVANCED_FILTER_GROUP_EMPTY_SEQUENCE         = 'ERROR_REPORT_ADVANCED_FILTER_GROUP_EMPTY_SEQUENCE';
		const ERROR_REPORT_ADVANCED_FILTER_GROUP_SEQUENCE_ALREADY_TAKEN = 'ERROR_REPORT_ADVANCED_FILTER_GROUP_SEQUENCE_ALREADY_TAKEN';

	}
