<?php

	class ReportStandardFilterException extends Exception {
		const ERROR_REPORT_STANDARD_FILTER_EMPTY_COLUMN_NAME   = 'ERROR_REPORT_STANDARD_FILTER_EMPTY_COLUMN_NAME';
		const ERROR_REPORT_STANDARD_FILTER_EMPTY_END_DATE      = 'ERROR_REPORT_STANDARD_FILTER_EMPTY_END_DATE';
		const ERROR_REPORT_STANDARD_FILTER_EMPTY_FIELD_NAME    = 'ERROR_REPORT_STANDARD_FILTER_EMPTY_FIELD_NAME';
		const ERROR_REPORT_STANDARD_FILTER_EMPTY_LABEL         = 'ERROR_REPORT_STANDARD_FILTER_EMPTY_LABEL';
		const ERROR_REPORT_STANDARD_FILTER_EMPTY_MODULE_NAME   = 'ERROR_REPORT_STANDARD_FILTER_EMPTY_MODULE_NAME';
		const ERROR_REPORT_STANDARD_FILTER_EMPTY_PERIOD        = 'ERROR_REPORT_STANDARD_FILTER_EMPTY_PERIOD';
		const ERROR_REPORT_STANDARD_FILTER_EMPTY_START_DATE    = 'ERROR_REPORT_STANDARD_FILTER_EMPTY_START_DATE';
		const ERROR_REPORT_STANDARD_FILTER_EMPTY_TABLE_NAME    = 'ERROR_REPORT_STANDARD_FILTER_EMPTY_TABLE_NAME';
		const ERROR_REPORT_STANDARD_FILTER_EMPTY_REPORT_ID     = 'ERROR_REPORT_STANDARD_FILTER_EMPTY_REPORT_ID';
		const ERROR_REPORT_STANDARD_FILTER_INVALID_COLUMN_NAME = 'ERROR_REPORT_STANDARD_FILTER_INVALID_COLUMN_NAME';
		const ERROR_REPORT_STANDARD_FILTER_INVALID_FIELD_NAME  = 'ERROR_REPORT_STANDARD_FILTER_INVALID_FIELD_NAME';
		const ERROR_REPORT_STANDARD_FILTER_INVALID_MODULE_NAME = 'ERROR_REPORT_STANDARD_FILTER_INVALID_MODULE_NAME';
		const ERROR_REPORT_STANDARD_FILTER_INVALID_TABLE_NAME  = 'ERROR_REPORT_STANDARD_FILTER_INVALID_TABLE_NAME';

	}
