<?php

	class ReportTemplateException extends Exception {
		const ERROR_REPORT_TEMPLATE_EMPTY               = 'ERROR_REPORT_TEMPLATE_EMPTY';
		const ERROR_REPORT_TEMPLATE_EMPTY_CODE          = 'ERROR_REPORT_TEMPLATE_EMPTY_CODE';
		const ERROR_REPORT_TEMPLATE_EMPTY_HAS_INVENTORY = 'ERROR_REPORT_TEMPLATE_EMPTY_HAS_INVENTORY';
		const ERROR_REPORT_TEMPLATE_EMPTY_IS_ACTIVE     = 'ERROR_REPORT_TEMPLATE_EMPTY_IS_ACTIVE';
		const ERROR_REPORT_TEMPLATE_EMPTY_MODULE_NAME   = 'ERROR_REPORT_TEMPLATE_EMPTY_MODULE_NAME';
		const ERROR_REPORT_TEMPLATE_EMPTY_NAME          = 'ERROR_REPORT_TEMPLATE_EMPTY_NAME';
		const ERROR_REPORT_TEMPLATE_INVALID_MODULE_NAME = 'ERROR_REPORT_TEMPLATE_INVALID_MODULE_NAME';

	}
