<?php

	class ReportScheduleException extends Exception {
		const ERROR_REPORT_SCHEDULE_EMPTY_DAY        = 'ERROR_REPORT_SCHEDULE_EMPTY_DAY';
		const ERROR_REPORT_SCHEDULE_EMPTY_FORMAT     = 'ERROR_REPORT_SCHEDULE_EMPTY_FORMAT';
		const ERROR_REPORT_SCHEDULE_EMPTY_FREQUENCY  = 'ERROR_REPORT_SCHEDULE_EMPTY_FREQUENCY';
		const ERROR_REPORT_SCHEDULE_EMPTY_MONTH      = 'ERROR_REPORT_SCHEDULE_EMPTY_MONTH';
		const ERROR_REPORT_SCHEDULE_EMPTY_RECIPIENTS = 'ERROR_REPORT_SCHEDULE_EMPTY_RECIPIENTS';
		const ERROR_REPORT_SCHEDULE_EMPTY_TIME       = 'ERROR_REPORT_SCHEDULE_EMPTY_TIME';
		const ERROR_REPORT_SCHEDULE_EMPTY_WEEKDAY    = 'ERROR_REPORT_SCHEDULE_EMPTY_WEEKDAY';

	}
