<?php

	class ReportException extends Exception {
		const ERROR_REPORT_FOLDER_DUPLICATE_NAME    = 'ERROR_REPORT_FOLDER_DUPLICATE_NAME';
		const ERROR_REPORT_FOLDER_EMPTY             = 'ERROR_REPORT_FOLDER_EMPTY';
		const ERROR_REPORT_FOLDER_EMPTY_NAME        = 'ERROR_REPORT_FOLDER_EMPTY_NAME';
		const ERROR_REPORT_FOLDER_INVALID_FOLDER_ID = 'ERROR_REPORT_FOLDER_INVALID_FOLDER_ID';

		const ERROR_REPORT_EMPTY                          = 'ERROR_REPORT_EMPTY';
		const ERROR_REPORT_EMPTY_APPLICATION_CODES        = 'ERROR_REPORT_EMPTY_APPLICATION_CODES';
		const ERROR_REPORT_EMPTY_FOLDER                   = 'ERROR_REPORT_EMPTY_FOLDER';
		const ERROR_REPORT_EMPTY_MODULE_NAME              = 'ERROR_REPORT_EMPTY_MODULE_NAME';
		const ERROR_REPORT_EMPTY_NAME                     = 'ERROR_REPORT_EMPTY_NAME';
		const ERROR_REPORT_EMPTY_OWNER                    = 'ERROR_REPORT_EMPTY_OWNER';
		const ERROR_REPORT_EMPTY_TYPE                     = 'ERROR_REPORT_EMPTY_TYPE';
		const ERROR_REPORT_EMPTY_VISIBILITY               = 'ERROR_REPORT_EMPTY_VISIBILITY';
		const ERROR_REPORT_INVALID_ADVANCED_FILTER_GROUP  = 'ERROR_REPORT_INVALID_ADVANCED_FILTER_GROUP';
		const ERROR_REPORT_INVALID_ADVANCED_FILTER_GROUPS = 'ERROR_REPORT_INVALID_ADVANCED_FILTER_GROUPS';
		const ERROR_REPORT_INVALID_COLUMN                 = 'ERROR_REPORT_INVALID_COLUMN';
		const ERROR_REPORT_INVALID_COLUMNS                = 'ERROR_REPORT_INVALID_COLUMNS';
		const ERROR_REPORT_INVALID_FOLDER                 = 'ERROR_REPORT_INVALID_FOLDER';
		const ERROR_REPORT_INVALID_MODULE_NAME            = 'ERROR_REPORT_INVALID_MODULE_NAME';
		const ERROR_REPORT_INVALID_SCHEDULE               = 'ERROR_REPORT_INVALID_SCHEDULE';
		const ERROR_REPORT_INVALID_SHARING_ENTITIES       = 'ERROR_REPORT_INVALID_SHARING_ENTITIES';
		const ERROR_REPORT_INVALID_SHARING_ENTITY         = 'ERROR_REPORT_INVALID_SHARING_ENTITY';
		const ERROR_REPORT_INVALID_SORT_COLUMN            = 'ERROR_REPORT_INVALID_SORT_COLUMN';
		const ERROR_REPORT_INVALID_SORT_COLUMNS           = 'ERROR_REPORT_INVALID_SORT_COLUMNS';
		const ERROR_REPORT_INVALID_STANDARD_FILTER        = 'ERROR_REPORT_INVALID_STANDARD_FILTER';
		const ERROR_REPORT_INVALID_TOTAL_COLUMN           = 'ERROR_REPORT_INVALID_TOTAL_COLUMN';
		const ERROR_REPORT_INVALID_TOTAL_COLUMNS          = 'ERROR_REPORT_INVALID_TOTAL_COLUMNS';

	}
