<?php

	class StandardPermissionProfileException extends Exception {
		const ERROR_STANDARD_PERMISSION_PROFILE_EMPTY                = 'ERROR_STANDARD_PERMISSION_PROFILE_EMPTY';
		const ERROR_STANDARD_PERMISSION_PROFILE_EMPTY_MODULE_NAME    = 'ERROR_STANDARD_PERMISSION_PROFILE_EMPTY_MODULE_NAME';
		const ERROR_STANDARD_PERMISSION_PROFILE_EMPTY_OPERATION      = 'ERROR_STANDARD_PERMISSION_PROFILE_EMPTY_OPERATION';
		const ERROR_STANDARD_PERMISSION_PROFILE_EMPTY_PROFILE_NAME   = 'ERROR_STANDARD_PERMISSION_PROFILE_EMPTY_PROFILE_NAME';
		const ERROR_STANDARD_PERMISSION_PROFILE_INVALID_MODULE_NAME  = 'ERROR_STANDARD_PERMISSION_PROFILE_INVALID_MODULE_NAME';
		const ERROR_STANDARD_PERMISSION_PROFILE_INVALID_OPERATION    = 'ERROR_STANDARD_PERMISSION_PROFILE_INVALID_OPERATION';
		const ERROR_STANDARD_PERMISSION_PROFILE_INVALID_PROFILE_NAME = 'ERROR_STANDARD_PERMISSION_PROFILE_INVALID_PROFILE_NAME';

	}
