<?php
	
	class SummaryReportException extends Exception 	{
		const ERROR_AGENT_EMPTY                 = 'ERROR_AGENT_EMPTY';
		const ERROR_AGREEMENT_EMPTY             = 'ERROR_AGREEMENT_EMPTY';
		const ERROR_INVALID_AGREEMENTS_STATUS   = 'ERROR_INVALID_AGREEMENTS_STATUS';
		const ERROR_TAB_NAME_EMPTY              = 'ERROR_TAB_NAME_EMPTY';
		const ERROR_DUE_DATE_EMPTY              = 'ERROR_DUE_DATE_EMPTY';
		const ERROR_INSTANCE_CODE_EMPTY         = 'ERROR_INSTANCE_CODE_EMPTY';
		const ERROR_INVALID_PERFORMANCES_STATUS = 'ERROR_INVALID_PERFORMANCES_STATUS';
		const ERROR_INVALID_REPORT_STATUS       = 'ERROR_INVALID_REPORT_STATUS';
		const ERROR_INVALID_REPORT_ID		    = 'ERROR_INVALID_REPORT_ID';
		const ERROR_PERFORMANCE_EMPTY           = 'ERROR_PERFORMANCE_EMPTY';
		const ERROR_PERFORMANCE_INDEX_EMPTY     = 'ERROR_PERFORMANCE_INDEX_EMPTY';
		const ERROR_PERFORMANCE_NAME_EMPTY      = 'ERROR_PERFORMANCE_NAME_EMPTY';
		const ERROR_PERIOD_DATE_EMPTY           = 'ERROR_PERIOD_DATE_EMPTY';
		const ERROR_START_DATE_EMPTY            = 'ERROR_START_DATE_EMPTY';
		const ERROR_USERS_INVOLVED_EMPTY        = 'ERROR_USERS_INVOLVED_EMPTY';
	}
