<?php

	class TaxConditionException extends Exception {
		const ERROR_TAX_CONDITION_EMPTY_ID            = 'ERROR_TAX_CONDITION_EMPTY_ID';
		const ERROR_TAX_CONDITION_EMPTY_COMPARATOR    = 'ERROR_TAX_CONDITION_EMPTY_COMPARATOR';
		const ERROR_TAX_CONDITION_EMPTY_GROUP_ID      = 'ERROR_TAX_CONDITION_EMPTY_GROUP_ID';
		const ERROR_TAX_CONDITION_EMPTY_OPERATOR      = 'ERROR_TAX_CONDITION_EMPTY_OPERATOR';
		const ERROR_TAX_CONDITION_EMPTY_TAX_ID        = 'ERROR_TAX_CONDITION_EMPTY_TAX_ID';
		const ERROR_TAX_CONDITION_EMPTY_VALUE         = 'ERROR_TAX_CONDITION_EMPTY_VALUE';
		const ERROR_TAX_CONDITION_EMPTY_VARIABLE_NAME = 'ERROR_TAX_CONDITION_EMPTY_VARIABLE_NAME';
		const ERROR_TAX_CONDITION_EMPTY_VARIABLE_TYPE = 'ERROR_TAX_CONDITION_EMPTY_VARIABLE_TYPE';

	}
