<?php

	class TaxException extends Exception {
		const ERROR_TAX_DUPLICATE_NAME          = 'ERROR_TAX_DUPLICATE_NAME';
		const ERROR_TAX_EMPTY                   = 'ERROR_TAX_EMPTY';
		const ERROR_TAX_EMPTY_CONDITION_GROUP   = 'ERROR_TAX_EMPTY_CONDITION_GROUP';
		const ERROR_TAX_EMPTY_DEFAULT           = 'ERROR_TAX_EMPTY_DEFAULT';
		const ERROR_TAX_EMPTY_ID                = 'ERROR_TAX_EMPTY_ID';
		const ERROR_TAX_EMPTY_NAME              = 'ERROR_TAX_EMPTY_NAME';
		const ERROR_TAX_EMPTY_PERCENTAGE        = 'ERROR_TAX_EMPTY_PERCENTAGE';
		const ERROR_TAX_INVALID_CONDITION_GROUP = 'ERROR_TAX_INVALID_CONDITION_GROUP';

	}
