<?php

	class UserException extends Exception {
		const ERROR_USER_DUPLICATE_USER_NAME = 'ERROR_USER_DUPLICATE_USER_NAME';
		const ERROR_USER_EMPTY_EMAIL         = 'ERROR_USER_EMPTY_EMAIL';
		const ERROR_USER_EMPTY_FIRST_NAME    = 'ERROR_USER_EMPTY_FIRST_NAME';
		const ERROR_USER_EMPTY_LAST_NAME     = 'ERROR_USER_EMPTY_LAST_NAME';
		const ERROR_USER_EMPTY_USER_NAME     = 'ERROR_USER_EMPTY_LAST_NAME';
		const ERROR_USER_INVALID_ROLE        = 'ERROR_USER_INVALID_ROLE';

	}
