<?php

	class UtilityProfileException extends Exception {
		const ERROR_UTILITY_PROFILE_EMPTY                = 'ERROR_UTILITY_PROFILE_EMPTY';
		const ERROR_UTILITY_PROFILE_EMPTY_MODULE_NAME    = 'ERROR_UTILITY_PROFILE_EMPTY_MODULE_NAME';
		const ERROR_UTILITY_PROFILE_EMPTY_PROFILE_NAME   = 'ERROR_UTILITY_PROFILE_EMPTY_PROFILE_NAME';
		const ERROR_UTILITY_PROFILE_EMPTY_UTILITY        = 'ERROR_UTILITY_PROFILE_EMPTY_UTILITY';
		const ERROR_UTILITY_PROFILE_INVALID_MODULE_NAME  = 'ERROR_UTILITY_PROFILE_INVALID_MODULE_NAME';
		const ERROR_UTILITY_PROFILE_INVALID_PROFILE_NAME = 'ERROR_UTILITY_PROFILE_INVALID_PROFILE_NAME';
		const ERROR_UTILITY_PROFILE_INVALID_UTILITY      = 'ERROR_UTILITY_PROFILE_INVALID_UTILITY';

	}
