<?php

	class ViewProfileException extends Exception {
		const ERROR_VIEW_PROFILE_EMPTY_PROFILE        = 'ERROR_VIEW_PROFILE_EMPTY_PROFILE';
		const ERROR_VIEW_PROFILE_EMPTY_MODULE_NAME    = 'ERROR_VIEW_PROFILE_EMPTY_MODULE_NAME';
		const ERROR_VIEW_PROFILE_EMPTY_PROFILE_NAME   = 'ERROR_VIEW_PROFILE_EMPTY_PROFILE_NAME';
		const ERROR_VIEW_PROFILE_EMPTY_VIEW_NAME      = 'ERROR_VIEW_PROFILE_EMPTY_VIEW_NAME';
		const ERROR_VIEW_PROFILE_INVALID_MODULE_NAME  = 'ERROR_VIEW_PROFILE_INVALID_MODULE_NAME';
		const ERROR_VIEW_PROFILE_INVALID_PROFILE_NAME = 'ERROR_VIEW_PROFILE_INVALID_PROFILE_NAME';
		const ERROR_VIEW_PROFILE_INVALID_VIEW_NAME    = 'ERROR_VIEW_PROFILE_INVALID_VIEW_NAME';

	}
