<?php

	class ViewAdvancedFilterException extends Exception {
		const ERROR_VIEW_ADVANCED_FILTER_EMPTY_COLUMN_NAME      = 'ERROR_VIEW_ADVANCED_FILTER_EMPTY_COLUMN_NAME';
		const ERROR_VIEW_ADVANCED_FILTER_EMPTY_COMPARATOR       = 'ERROR_VIEW_ADVANCED_FILTER_EMPTY_COMPARATOR';
		const ERROR_VIEW_ADVANCED_FILTER_EMPTY_DATA_TYPE        = 'ERROR_VIEW_ADVANCED_FILTER_EMPTY_DATA_TYPE';
		const ERROR_VIEW_ADVANCED_FILTER_EMPTY_FIELD_NAME       = 'ERROR_VIEW_ADVANCED_FILTER_EMPTY_FIELD_NAME';
		const ERROR_VIEW_ADVANCED_FILTER_EMPTY_GROUP_ID         = 'ERROR_VIEW_ADVANCED_FILTER_EMPTY_GROUP_ID';
		const ERROR_VIEW_ADVANCED_FILTER_EMPTY_LABEL            = 'ERROR_VIEW_ADVANCED_FILTER_EMPTY_LABEL';
		const ERROR_VIEW_ADVANCED_FILTER_EMPTY_MODULE_NAME      = 'ERROR_VIEW_ADVANCED_FILTER_EMPTY_MODULE_NAME';
		const ERROR_VIEW_ADVANCED_FILTER_EMPTY_SEQUENCE         = 'ERROR_VIEW_ADVANCED_FILTER_EMPTY_SEQUENCE';
		const ERROR_VIEW_ADVANCED_FILTER_EMPTY_TABLE_NAME       = 'ERROR_VIEW_ADVANCED_FILTER_EMPTY_TABLE_NAME';
		const ERROR_VIEW_ADVANCED_FILTER_EMPTY_VIEW_ID          = 'ERROR_VIEW_ADVANCED_FILTER_EMPTY_VIEW_ID';
		const ERROR_VIEW_ADVANCED_FILTER_INVALID_FILTER         = 'ERROR_VIEW_ADVANCED_FILTER_INVALID_FILTER';
		const ERROR_VIEW_ADVANCED_FILTER_INVALID_COLUMN_NAME    = 'ERROR_VIEW_ADVANCED_FILTER_INVALID_COLUMN_NAME';
		const ERROR_VIEW_ADVANCED_FILTER_INVALID_FIELD_NAME     = 'ERROR_VIEW_ADVANCED_FILTER_INVALID_FIELD_NAME';
		const ERROR_VIEW_ADVANCED_FILTER_INVALID_MODULE_NAME    = 'ERROR_VIEW_ADVANCED_FILTER_INVALID_MODULE_NAME';
		const ERROR_VIEW_ADVANCED_FILTER_INVALID_TABLE_NAME     = 'ERROR_VIEW_ADVANCED_FILTER_INVALID_TABLE_NAME';
		const ERROR_VIEW_ADVANCED_FILTER_SEQUENCE_ALREADY_TAKEN = 'ERROR_VIEW_ADVANCED_FILTER_SEQUENCE_ALREADY_TAKEN';

	}
