<?php

	class ViewAdvancedFilterGroupException extends Exception {
		const ERROR_VIEW_ADVANCED_FILTER_GROUP_EMPTY_FILTERS          = 'ERROR_VIEW_ADVANCED_FILTER_GROUP_EMPTY_FILTERS';
		const ERROR_VIEW_ADVANCED_FILTER_GROUP_EMPTY_SEQUENCE         = 'ERROR_VIEW_ADVANCED_FILTER_GROUP_EMPTY_SEQUENCE';
		const ERROR_VIEW_ADVANCED_FILTER_GROUP_EMPTY_VIEW_ID          = 'ERROR_VIEW_ADVANCED_FILTER_GROUP_EMPTY_VIEW_ID';
		const ERROR_VIEW_ADVANCED_FILTER_GROUP_SEQUENCE_ALREADY_TAKEN = 'ERROR_VIEW_ADVANCED_FILTER_GROUP_SEQUENCE_ALREADY_TAKEN';

	}
