<?php

	class ViewException extends Exception {
		const ERROR_VIEW_DUPLICATE_NAME                 = 'ERROR_VIEW_DUPLICATE_NAME';
		const ERROR_VIEW_EMPTY                          = 'ERROR_VIEW_EMPTY';
		const ERROR_VIEW_EMPTY_GROUP_NAME               = 'ERROR_VIEW_EMPTY_GROUP_NAME';
		const ERROR_VIEW_EMPTY_MODULE_NAME              = 'ERROR_VIEW_EMPTY_MODULE_NAME';
		const ERROR_VIEW_EMPTY_NAME                     = 'ERROR_VIEW_EMPTY_NAME';
		const ERROR_VIEW_EMPTY_OWNER                    = 'ERROR_VIEW_EMPTY_OWNER';
		const ERROR_VIEW_INVALID_ADVANCED_FILTER_GROUP  = 'ERROR_VIEW_INVALID_ADVANCED_FILTER_GROUP';
		const ERROR_VIEW_INVALID_ADVANCED_FILTER_GROUPS = 'ERROR_VIEW_INVALID_ADVANCED_FILTER_GROUPS';
		const ERROR_VIEW_INVALID_COLOR_FILTER_GROUP     = 'ERROR_VIEW_INVALID_COLOR_FILTER_GROUP';
		const ERROR_VIEW_INVALID_COLOR_FILTER_GROUPS    = 'ERROR_VIEW_INVALID_COLOR_FILTER_GROUPS';
		const ERROR_VIEW_INVALID_COLUMN                 = 'ERROR_VIEW_INVALID_COLUMN';
		const ERROR_VIEW_INVALID_COLUMNS                = 'ERROR_VIEW_INVALID_COLUMNS';
		const ERROR_VIEW_INVALID_MODULE_NAME            = 'ERROR_VIEW_INVALID_MODULE_NAME';
		const ERROR_VIEW_INVALID_STANDARD_FILTER        = 'ERROR_VIEW_INVALID_STANDARD_FILTER';

	}
