<?php
	
	class PlatziIssabelException extends Exception {
		const DATABASE_CONNECTION_ERROR     = 'DATABASE CONNECTION ERROR';
		const ERROR_CONFIG_FILE_NOT_FOUND   = 'ERROR_CONFIG_FILE_NOT_FOUND';
		const ERROR_ESTABLISHING_CONNECTION = 'ERROR_ESTABLISHING_CONNECTION_TO_ISSABEL';
		const ERROR_MONITOR_ID_EMPTY        = 'ERROR_MONITOR_ID_EMPTY';
	}