<?php

	interface BackgroundTaskParameterConfigurationInterface {
		const PARAMETER_TYPE_CALCULATED_DATE         = 'CALCULATED DATE';
		const PARAMETER_TYPE_CUSTOM_SQL              = 'CUSTOM SQL';
		const PARAMETER_TYPE_EMAIL_SOURCE_FIELD      = 'EMAIL SOURCE FIELD';
		const PARAMETER_TYPE_FORMULA                 = 'FORMULA';
		const PARAMETER_TYPE_INSTANCE_EMAILS         = 'INSTANCE EMAILS';
		const PARAMETER_TYPE_JSON                    = 'JSON';
		const PARAMETER_TYPE_LITERAL                 = 'LITERAL';
		const PARAMETER_TYPE_NOTIFICATIONS           = 'NOTIFICATIONS';
		const PARAMETER_TYPE_PREVIOUS_OUTPUT         = 'PREVIOUS OUTPUT';
		const PARAMETER_TYPE_RECORD_ID_PROJECT_FIELD = 'RECORD ID PROJECT FIELD';
		const PARAMETER_TYPE_RECORD_ID_SOURCE_FIELD  = 'RECORD ID SOURCE FIELD';
		const PARAMETER_TYPE_RELATED_SOURCE_FIELD    = 'RELATED SOURCE FIELD';
		const PARAMETER_TYPE_SOURCE_FIELD            = 'SOURCE FIELD';
		const PARAMETER_TYPE_SOURCE_GRID_FIELD       = 'SOURCE GRID FIELD';
		const PARAMETER_TYPE_VARIABLE                = 'VARIABLE';

		const OPTION_TYPE_HANDLER = 'HANDLER';
		const OPTION_TYPE_JSON    = 'JSON';
		const OPTION_TYPE_LITERAL = 'LITERAL';
		const OPTION_TYPE_SQL     = 'SQL';

	}
