<?php
	class QuestionException extends Exception {
		const ERROR_CALCULATION_TYPE_EMPTY    = 'ERROR_CALCULATION_TYPE_EMPTY';
		const ERROR_EXTENSION_NO_ALLOWED      = 'EXTENSION_NO_ALLOWED, PLACE_CHOOSE A PNG FILE';
		const ERROR_FILE_TOO_BIG              = 'FILE_TOO_BIG, FILE SIZE MUST BE MAX 2MB';
		const ERROR_QUESTION_EMPTY            = 'ERROR_QUESTION_EMPTY';
		const ERROR_QUESTION_FORM_EMPTY       = 'ERROR_QUESTION_FORM_EMPTY';
		const ERROR_QUESTION_GROUP_EMPTY      = 'ERROR_QUESTION_GROUP_EMPTY';
		const ERROR_QUESTION_STAGE_EMPTY      = 'ERROR_QUESTION_STAGE_EMPTY';
		const ERROR_QUESTION_TYPE_EMPTY       = 'ERROR_QUESTION_TYPE_EMPTY';
		const ERROR_QUESTION_PUCTUATION_EMPTY = 'ERROR_QUESTION_PUCTUATION_EMPTY';
		const ERROR_QUESTION_WEIGHING_EMPTY   = 'ERROR_QUESTION_WEIGHING_EMPTY';
	}
