<?php
	class OkrsException extends Exception {
		const ERROR_OKRS_EMPTY_ACTUAL_VALUE   = 'ERROR_OKRS_EMPTY_ACTUL_VALUE';
		const ERROR_OKRS_EMPTY_COMPANY_AREA   = 'ERROR_OKRS_EMPTY_COMPANY_AREA';
		const ERROR_OKRS_EMPTY_COMPANY_PHASE  = 'ERROR_OKRS_EMPTY_COMPANY_PHASE';
		const ERROR_OKRS_EMPTY_COMPANY_TYPE   = 'ERROR_OKRS_EMPTY_COMPANY_TYPE';
		const ERROR_OKRS_EMPTY_FREQUENCY      = 'ERROR_OKRS_EMPTY_FREQUENCY';
		const ERROR_OKRS_EMPTY_OBJECTIVE_ID   = 'ERROR_OKRS_EMPTY_OBJECTIVE_ID';
		const ERROR_OKRS_EMPTY_KEY_RESULTS    = 'ERROR_VIEW_EMPTY_KEY_RESULTS';
		const ERROR_OKRS_EMPTY_GOAL_VALUE     = 'ERROR_OKRS_EMPTY_GOAL_VALUE';
		const ERROR_OKRS_EMPTY_TODO_OBJECTIVE = 'ERROR_OKRS_EMPTY_TODO_OBJECTIVE';
	}