<?php

	interface OkrsInterface {
		const OKRS_COMPANY_AREA  = array ('SALES', 'MARKENTING', 'OPERATIONS', 'ADMINISTRATION', 'TREASURY', 'TECHNOLOGY');
		const OKRS_COMPANY_PHASE = array ('IDEA', 'START_DESERT_CROSSING', 'IRREGULAR_GROWTH', 'STABLE_GROWTH', 'OPTIMAL_OPERATION');
		const OKRS_COMPANY_TYPE  = array ('DISTRIBUTION', 'PRODUCTION', 'TYPE_SALES', 'SERVICES');
		const OKRS_FREQUENCY     = array ('MONTHLY', 'QUARTERLY', 'SEMIANNUAL', 'ANNUAL');
		const OKRS_IS_ON_BORDING = array ('YES', 'NO');
		const OKRS_STATUS        = array ('ENABLED', 'DISABLED');
	}
