<?php

	class FolderException extends Exception {
		const ERROR_CREATE_EMPTY_CATEGORY_NAME   = 'ERROR_CREATE_EMPTY_CATEGORY_NAME';
		const ERROR_CREATE_EMPTY_FILE_NAME       = 'ERROR_CREATE_EMPTY_FILE_NAME';
		const ERROR_CREATE_EMPTY_FILE_URL        = 'ERROR_CREATE_EMPTY_FILE_URL';
		const ERROR_CREATE_EMPTY_FOLDER_ID       = 'ERROR_CREATE_EMPTY_FOLDER_ID';
		const ERROR_CREATE_EMPTY_FOLDER_NAME     = 'ERROR_CREATE_EMPTY_FOLDER_NAME';
		const ERROR_CREATE_EMPTY_OBJECT_CATEGORY = 'ERROR_CREATE_EMPTY_OBJECT_CATEGORY';
		const ERROR_CREATE_EMPTY_OBJECT_FILE     = 'ERROR_CREATE_EMPTY_OBJECT_FILE';
		const ERROR_CREATE_EMPTY_OBJECT_FOLDER   = 'ERROR_CREATE_EMPTY_OBJECT_FOLDER';
		const ERROR_CREATE_DUPLICATE_FOLDER      = 'ERROR_CREATE_DUPLICATE_FOLDER';
		const ERROR_EXTENSION_NO_ALLOWED         = 'EXTENSION_NO_ALLOWED, PLACE_CHOOSE A PNG FILE';
		const ERROR_FILE_TOO_BIG                 = 'FILE_TOO_BIG, FILE SIZE MUST BE MAX 2MB';
		const ERROR_FILE_PUBLIC_URL              = 'ERROR_FILE_PUBLIC_URL';
	}
